// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tcpmsg.proto

package tcpmsg_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import github_com_golang_protobuf_proto "github.com/golang/protobuf/proto"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProtocolId int32

const (
	ProtocolId_PID_P2P ProtocolId = 0
	ProtocolId_PID_EXT ProtocolId = 255
)

var ProtocolId_name = map[int32]string{
	0:   "PID_P2P",
	255: "PID_EXT",
}
var ProtocolId_value = map[string]int32{
	"PID_P2P": 0,
	"PID_EXT": 255,
}

func (x ProtocolId) Enum() *ProtocolId {
	p := new(ProtocolId)
	*p = x
	return p
}
func (x ProtocolId) String() string {
	return proto.EnumName(ProtocolId_name, int32(x))
}
func (x *ProtocolId) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProtocolId_value, data, "ProtocolId")
	if err != nil {
		return err
	}
	*x = ProtocolId(value)
	return nil
}
func (ProtocolId) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_tcpmsg_0e96c110557f47de, []int{0}
}

type MessageId int32

const (
	MessageId_MID_HANDSHAKE   MessageId = 0
	MessageId_MID_PING        MessageId = 1
	MessageId_MID_PONG        MessageId = 2
	MessageId_MID_TX          MessageId = 3
	MessageId_MID_EVENT       MessageId = 4
	MessageId_MID_BLOCKHEADER MessageId = 5
	MessageId_MID_BLOCK       MessageId = 6
)

var MessageId_name = map[int32]string{
	0: "MID_HANDSHAKE",
	1: "MID_PING",
	2: "MID_PONG",
	3: "MID_TX",
	4: "MID_EVENT",
	5: "MID_BLOCKHEADER",
	6: "MID_BLOCK",
}
var MessageId_value = map[string]int32{
	"MID_HANDSHAKE":   0,
	"MID_PING":        1,
	"MID_PONG":        2,
	"MID_TX":          3,
	"MID_EVENT":       4,
	"MID_BLOCKHEADER": 5,
	"MID_BLOCK":       6,
}

func (x MessageId) Enum() *MessageId {
	p := new(MessageId)
	*p = x
	return p
}
func (x MessageId) String() string {
	return proto.EnumName(MessageId_name, int32(x))
}
func (x *MessageId) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageId_value, data, "MessageId")
	if err != nil {
		return err
	}
	*x = MessageId(value)
	return nil
}
func (MessageId) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_tcpmsg_0e96c110557f47de, []int{1}
}

type P2PPackage struct {
	Pid                  *ProtocolId `protobuf:"varint,1,req,name=Pid,enum=tcpmsg.pb.ProtocolId" json:"Pid,omitempty"`
	ExtMid               *MessageId  `protobuf:"varint,2,opt,name=ExtMid,enum=tcpmsg.pb.MessageId" json:"ExtMid,omitempty"`
	ExtKey               []byte      `protobuf:"bytes,3,opt,name=ExtKey" json:"ExtKey,omitempty"`
	PayloadLength        *uint32     `protobuf:"varint,4,req,name=PayloadLength" json:"PayloadLength,omitempty"`
	Payload              []byte      `protobuf:"bytes,5,opt,name=Payload" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *P2PPackage) Reset()         { *m = P2PPackage{} }
func (m *P2PPackage) String() string { return proto.CompactTextString(m) }
func (*P2PPackage) ProtoMessage()    {}
func (*P2PPackage) Descriptor() ([]byte, []int) {
	return fileDescriptor_tcpmsg_0e96c110557f47de, []int{0}
}
func (m *P2PPackage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *P2PPackage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_P2PPackage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *P2PPackage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P2PPackage.Merge(dst, src)
}
func (m *P2PPackage) XXX_Size() int {
	return m.Size()
}
func (m *P2PPackage) XXX_DiscardUnknown() {
	xxx_messageInfo_P2PPackage.DiscardUnknown(m)
}

var xxx_messageInfo_P2PPackage proto.InternalMessageInfo

func (m *P2PPackage) GetPid() ProtocolId {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ProtocolId_PID_P2P
}

func (m *P2PPackage) GetExtMid() MessageId {
	if m != nil && m.ExtMid != nil {
		return *m.ExtMid
	}
	return MessageId_MID_HANDSHAKE
}

func (m *P2PPackage) GetExtKey() []byte {
	if m != nil {
		return m.ExtKey
	}
	return nil
}

func (m *P2PPackage) GetPayloadLength() uint32 {
	if m != nil && m.PayloadLength != nil {
		return *m.PayloadLength
	}
	return 0
}

func (m *P2PPackage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type P2PMessage struct {
	Mid                  *MessageId            `protobuf:"varint,1,req,name=mid,enum=tcpmsg.pb.MessageId" json:"mid,omitempty"`
	Handshake            *P2PMessage_Handshake `protobuf:"bytes,2,opt,name=handshake" json:"handshake,omitempty"`
	Ping                 *P2PMessage_Ping      `protobuf:"bytes,3,opt,name=ping" json:"ping,omitempty"`
	Pong                 *P2PMessage_Pong      `protobuf:"bytes,4,opt,name=pong" json:"pong,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *P2PMessage) Reset()         { *m = P2PMessage{} }
func (m *P2PMessage) String() string { return proto.CompactTextString(m) }
func (*P2PMessage) ProtoMessage()    {}
func (*P2PMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_tcpmsg_0e96c110557f47de, []int{1}
}
func (m *P2PMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *P2PMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_P2PMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *P2PMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P2PMessage.Merge(dst, src)
}
func (m *P2PMessage) XXX_Size() int {
	return m.Size()
}
func (m *P2PMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_P2PMessage.DiscardUnknown(m)
}

var xxx_messageInfo_P2PMessage proto.InternalMessageInfo

func (m *P2PMessage) GetMid() MessageId {
	if m != nil && m.Mid != nil {
		return *m.Mid
	}
	return MessageId_MID_HANDSHAKE
}

func (m *P2PMessage) GetHandshake() *P2PMessage_Handshake {
	if m != nil {
		return m.Handshake
	}
	return nil
}

func (m *P2PMessage) GetPing() *P2PMessage_Ping {
	if m != nil {
		return m.Ping
	}
	return nil
}

func (m *P2PMessage) GetPong() *P2PMessage_Pong {
	if m != nil {
		return m.Pong
	}
	return nil
}

type P2PMessage_Protocol struct {
	Pid                  *ProtocolId `protobuf:"varint,1,req,name=Pid,enum=tcpmsg.pb.ProtocolId" json:"Pid,omitempty"`
	Ver                  []byte      `protobuf:"bytes,2,req,name=Ver" json:"Ver,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *P2PMessage_Protocol) Reset()         { *m = P2PMessage_Protocol{} }
func (m *P2PMessage_Protocol) String() string { return proto.CompactTextString(m) }
func (*P2PMessage_Protocol) ProtoMessage()    {}
func (*P2PMessage_Protocol) Descriptor() ([]byte, []int) {
	return fileDescriptor_tcpmsg_0e96c110557f47de, []int{1, 0}
}
func (m *P2PMessage_Protocol) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *P2PMessage_Protocol) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_P2PMessage_Protocol.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *P2PMessage_Protocol) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P2PMessage_Protocol.Merge(dst, src)
}
func (m *P2PMessage_Protocol) XXX_Size() int {
	return m.Size()
}
func (m *P2PMessage_Protocol) XXX_DiscardUnknown() {
	xxx_messageInfo_P2PMessage_Protocol.DiscardUnknown(m)
}

var xxx_messageInfo_P2PMessage_Protocol proto.InternalMessageInfo

func (m *P2PMessage_Protocol) GetPid() ProtocolId {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ProtocolId_PID_P2P
}

func (m *P2PMessage_Protocol) GetVer() []byte {
	if m != nil {
		return m.Ver
	}
	return nil
}

type P2PMessage_Handshake struct {
	SubNetId             []byte                 `protobuf:"bytes,1,req,name=SubNetId" json:"SubNetId,omitempty"`
	NodeId               []byte                 `protobuf:"bytes,2,req,name=NodeId" json:"NodeId,omitempty"`
	IP                   []byte                 `protobuf:"bytes,3,req,name=IP" json:"IP,omitempty"`
	UDP                  *uint32                `protobuf:"varint,4,req,name=UDP" json:"UDP,omitempty"`
	TCP                  *uint32                `protobuf:"varint,5,req,name=TCP" json:"TCP,omitempty"`
	ProtoNum             *uint32                `protobuf:"varint,6,req,name=ProtoNum" json:"ProtoNum,omitempty"`
	Protocols            []*P2PMessage_Protocol `protobuf:"bytes,7,rep,name=Protocols" json:"Protocols,omitempty"`
	SignR                *int32                 `protobuf:"varint,8,req,name=SignR" json:"SignR,omitempty"`
	R                    []byte                 `protobuf:"bytes,9,req,name=R" json:"R,omitempty"`
	SignS                *int32                 `protobuf:"varint,10,req,name=SignS" json:"SignS,omitempty"`
	S                    []byte                 `protobuf:"bytes,11,req,name=S" json:"S,omitempty"`
	Extra                []byte                 `protobuf:"bytes,12,opt,name=Extra" json:"Extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *P2PMessage_Handshake) Reset()         { *m = P2PMessage_Handshake{} }
func (m *P2PMessage_Handshake) String() string { return proto.CompactTextString(m) }
func (*P2PMessage_Handshake) ProtoMessage()    {}
func (*P2PMessage_Handshake) Descriptor() ([]byte, []int) {
	return fileDescriptor_tcpmsg_0e96c110557f47de, []int{1, 1}
}
func (m *P2PMessage_Handshake) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *P2PMessage_Handshake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_P2PMessage_Handshake.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *P2PMessage_Handshake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P2PMessage_Handshake.Merge(dst, src)
}
func (m *P2PMessage_Handshake) XXX_Size() int {
	return m.Size()
}
func (m *P2PMessage_Handshake) XXX_DiscardUnknown() {
	xxx_messageInfo_P2PMessage_Handshake.DiscardUnknown(m)
}

var xxx_messageInfo_P2PMessage_Handshake proto.InternalMessageInfo

func (m *P2PMessage_Handshake) GetSubNetId() []byte {
	if m != nil {
		return m.SubNetId
	}
	return nil
}

func (m *P2PMessage_Handshake) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *P2PMessage_Handshake) GetIP() []byte {
	if m != nil {
		return m.IP
	}
	return nil
}

func (m *P2PMessage_Handshake) GetUDP() uint32 {
	if m != nil && m.UDP != nil {
		return *m.UDP
	}
	return 0
}

func (m *P2PMessage_Handshake) GetTCP() uint32 {
	if m != nil && m.TCP != nil {
		return *m.TCP
	}
	return 0
}

func (m *P2PMessage_Handshake) GetProtoNum() uint32 {
	if m != nil && m.ProtoNum != nil {
		return *m.ProtoNum
	}
	return 0
}

func (m *P2PMessage_Handshake) GetProtocols() []*P2PMessage_Protocol {
	if m != nil {
		return m.Protocols
	}
	return nil
}

func (m *P2PMessage_Handshake) GetSignR() int32 {
	if m != nil && m.SignR != nil {
		return *m.SignR
	}
	return 0
}

func (m *P2PMessage_Handshake) GetR() []byte {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *P2PMessage_Handshake) GetSignS() int32 {
	if m != nil && m.SignS != nil {
		return *m.SignS
	}
	return 0
}

func (m *P2PMessage_Handshake) GetS() []byte {
	if m != nil {
		return m.S
	}
	return nil
}

func (m *P2PMessage_Handshake) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

type P2PMessage_Ping struct {
	Seq                  *uint64  `protobuf:"varint,1,req,name=seq" json:"seq,omitempty"`
	Extra                []byte   `protobuf:"bytes,2,opt,name=Extra" json:"Extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *P2PMessage_Ping) Reset()         { *m = P2PMessage_Ping{} }
func (m *P2PMessage_Ping) String() string { return proto.CompactTextString(m) }
func (*P2PMessage_Ping) ProtoMessage()    {}
func (*P2PMessage_Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_tcpmsg_0e96c110557f47de, []int{1, 2}
}
func (m *P2PMessage_Ping) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *P2PMessage_Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_P2PMessage_Ping.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *P2PMessage_Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P2PMessage_Ping.Merge(dst, src)
}
func (m *P2PMessage_Ping) XXX_Size() int {
	return m.Size()
}
func (m *P2PMessage_Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_P2PMessage_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_P2PMessage_Ping proto.InternalMessageInfo

func (m *P2PMessage_Ping) GetSeq() uint64 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

func (m *P2PMessage_Ping) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

type P2PMessage_Pong struct {
	Seq                  *uint64  `protobuf:"varint,1,req,name=seq" json:"seq,omitempty"`
	Extra                []byte   `protobuf:"bytes,2,opt,name=Extra" json:"Extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *P2PMessage_Pong) Reset()         { *m = P2PMessage_Pong{} }
func (m *P2PMessage_Pong) String() string { return proto.CompactTextString(m) }
func (*P2PMessage_Pong) ProtoMessage()    {}
func (*P2PMessage_Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_tcpmsg_0e96c110557f47de, []int{1, 3}
}
func (m *P2PMessage_Pong) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *P2PMessage_Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_P2PMessage_Pong.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *P2PMessage_Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P2PMessage_Pong.Merge(dst, src)
}
func (m *P2PMessage_Pong) XXX_Size() int {
	return m.Size()
}
func (m *P2PMessage_Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_P2PMessage_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_P2PMessage_Pong proto.InternalMessageInfo

func (m *P2PMessage_Pong) GetSeq() uint64 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

func (m *P2PMessage_Pong) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

func init() {
	proto.RegisterType((*P2PPackage)(nil), "tcpmsg.pb.P2PPackage")
	proto.RegisterType((*P2PMessage)(nil), "tcpmsg.pb.P2PMessage")
	proto.RegisterType((*P2PMessage_Protocol)(nil), "tcpmsg.pb.P2PMessage.Protocol")
	proto.RegisterType((*P2PMessage_Handshake)(nil), "tcpmsg.pb.P2PMessage.Handshake")
	proto.RegisterType((*P2PMessage_Ping)(nil), "tcpmsg.pb.P2PMessage.Ping")
	proto.RegisterType((*P2PMessage_Pong)(nil), "tcpmsg.pb.P2PMessage.Pong")
	proto.RegisterEnum("tcpmsg.pb.ProtocolId", ProtocolId_name, ProtocolId_value)
	proto.RegisterEnum("tcpmsg.pb.MessageId", MessageId_name, MessageId_value)
}
func (m *P2PPackage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *P2PPackage) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Pid == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x8
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(*m.Pid))
	}
	if m.ExtMid != nil {
		dAtA[i] = 0x10
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(*m.ExtMid))
	}
	if m.ExtKey != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(len(m.ExtKey)))
		i += copy(dAtA[i:], m.ExtKey)
	}
	if m.PayloadLength == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x20
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(*m.PayloadLength))
	}
	if m.Payload != nil {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(len(m.Payload)))
		i += copy(dAtA[i:], m.Payload)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *P2PMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *P2PMessage) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Mid == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x8
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(*m.Mid))
	}
	if m.Handshake != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(m.Handshake.Size()))
		n1, err := m.Handshake.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.Ping != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(m.Ping.Size()))
		n2, err := m.Ping.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.Pong != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(m.Pong.Size()))
		n3, err := m.Pong.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *P2PMessage_Protocol) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *P2PMessage_Protocol) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Pid == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x8
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(*m.Pid))
	}
	if m.Ver == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(len(m.Ver)))
		i += copy(dAtA[i:], m.Ver)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *P2PMessage_Handshake) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *P2PMessage_Handshake) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.SubNetId == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(len(m.SubNetId)))
		i += copy(dAtA[i:], m.SubNetId)
	}
	if m.NodeId == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(len(m.NodeId)))
		i += copy(dAtA[i:], m.NodeId)
	}
	if m.IP == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(len(m.IP)))
		i += copy(dAtA[i:], m.IP)
	}
	if m.UDP == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x20
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(*m.UDP))
	}
	if m.TCP == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x28
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(*m.TCP))
	}
	if m.ProtoNum == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x30
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(*m.ProtoNum))
	}
	if len(m.Protocols) > 0 {
		for _, msg := range m.Protocols {
			dAtA[i] = 0x3a
			i++
			i = encodeVarintTcpmsg(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.SignR == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x40
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(*m.SignR))
	}
	if m.R == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(len(m.R)))
		i += copy(dAtA[i:], m.R)
	}
	if m.SignS == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x50
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(*m.SignS))
	}
	if m.S == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x5a
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(len(m.S)))
		i += copy(dAtA[i:], m.S)
	}
	if m.Extra != nil {
		dAtA[i] = 0x62
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(len(m.Extra)))
		i += copy(dAtA[i:], m.Extra)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *P2PMessage_Ping) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *P2PMessage_Ping) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Seq == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x8
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(*m.Seq))
	}
	if m.Extra != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(len(m.Extra)))
		i += copy(dAtA[i:], m.Extra)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *P2PMessage_Pong) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *P2PMessage_Pong) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Seq == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x8
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(*m.Seq))
	}
	if m.Extra != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(len(m.Extra)))
		i += copy(dAtA[i:], m.Extra)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintTcpmsg(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *P2PPackage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pid != nil {
		n += 1 + sovTcpmsg(uint64(*m.Pid))
	}
	if m.ExtMid != nil {
		n += 1 + sovTcpmsg(uint64(*m.ExtMid))
	}
	if m.ExtKey != nil {
		l = len(m.ExtKey)
		n += 1 + l + sovTcpmsg(uint64(l))
	}
	if m.PayloadLength != nil {
		n += 1 + sovTcpmsg(uint64(*m.PayloadLength))
	}
	if m.Payload != nil {
		l = len(m.Payload)
		n += 1 + l + sovTcpmsg(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *P2PMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Mid != nil {
		n += 1 + sovTcpmsg(uint64(*m.Mid))
	}
	if m.Handshake != nil {
		l = m.Handshake.Size()
		n += 1 + l + sovTcpmsg(uint64(l))
	}
	if m.Ping != nil {
		l = m.Ping.Size()
		n += 1 + l + sovTcpmsg(uint64(l))
	}
	if m.Pong != nil {
		l = m.Pong.Size()
		n += 1 + l + sovTcpmsg(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *P2PMessage_Protocol) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pid != nil {
		n += 1 + sovTcpmsg(uint64(*m.Pid))
	}
	if m.Ver != nil {
		l = len(m.Ver)
		n += 1 + l + sovTcpmsg(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *P2PMessage_Handshake) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SubNetId != nil {
		l = len(m.SubNetId)
		n += 1 + l + sovTcpmsg(uint64(l))
	}
	if m.NodeId != nil {
		l = len(m.NodeId)
		n += 1 + l + sovTcpmsg(uint64(l))
	}
	if m.IP != nil {
		l = len(m.IP)
		n += 1 + l + sovTcpmsg(uint64(l))
	}
	if m.UDP != nil {
		n += 1 + sovTcpmsg(uint64(*m.UDP))
	}
	if m.TCP != nil {
		n += 1 + sovTcpmsg(uint64(*m.TCP))
	}
	if m.ProtoNum != nil {
		n += 1 + sovTcpmsg(uint64(*m.ProtoNum))
	}
	if len(m.Protocols) > 0 {
		for _, e := range m.Protocols {
			l = e.Size()
			n += 1 + l + sovTcpmsg(uint64(l))
		}
	}
	if m.SignR != nil {
		n += 1 + sovTcpmsg(uint64(*m.SignR))
	}
	if m.R != nil {
		l = len(m.R)
		n += 1 + l + sovTcpmsg(uint64(l))
	}
	if m.SignS != nil {
		n += 1 + sovTcpmsg(uint64(*m.SignS))
	}
	if m.S != nil {
		l = len(m.S)
		n += 1 + l + sovTcpmsg(uint64(l))
	}
	if m.Extra != nil {
		l = len(m.Extra)
		n += 1 + l + sovTcpmsg(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *P2PMessage_Ping) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Seq != nil {
		n += 1 + sovTcpmsg(uint64(*m.Seq))
	}
	if m.Extra != nil {
		l = len(m.Extra)
		n += 1 + l + sovTcpmsg(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *P2PMessage_Pong) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Seq != nil {
		n += 1 + sovTcpmsg(uint64(*m.Seq))
	}
	if m.Extra != nil {
		l = len(m.Extra)
		n += 1 + l + sovTcpmsg(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovTcpmsg(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozTcpmsg(x uint64) (n int) {
	return sovTcpmsg(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *P2PPackage) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTcpmsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: P2PPackage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: P2PPackage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pid", wireType)
			}
			var v ProtocolId
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (ProtocolId(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Pid = &v
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtMid", wireType)
			}
			var v MessageId
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (MessageId(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ExtMid = &v
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTcpmsg
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExtKey = append(m.ExtKey[:0], dAtA[iNdEx:postIndex]...)
			if m.ExtKey == nil {
				m.ExtKey = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PayloadLength", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.PayloadLength = &v
			hasFields[0] |= uint64(0x00000002)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTcpmsg
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = append(m.Payload[:0], dAtA[iNdEx:postIndex]...)
			if m.Payload == nil {
				m.Payload = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTcpmsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTcpmsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *P2PMessage) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTcpmsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: P2PMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: P2PMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mid", wireType)
			}
			var v MessageId
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (MessageId(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Mid = &v
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Handshake", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTcpmsg
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Handshake == nil {
				m.Handshake = &P2PMessage_Handshake{}
			}
			if err := m.Handshake.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ping", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTcpmsg
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Ping == nil {
				m.Ping = &P2PMessage_Ping{}
			}
			if err := m.Ping.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pong", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTcpmsg
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pong == nil {
				m.Pong = &P2PMessage_Pong{}
			}
			if err := m.Pong.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTcpmsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTcpmsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *P2PMessage_Protocol) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTcpmsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Protocol: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Protocol: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pid", wireType)
			}
			var v ProtocolId
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (ProtocolId(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Pid = &v
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ver", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTcpmsg
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ver = append(m.Ver[:0], dAtA[iNdEx:postIndex]...)
			if m.Ver == nil {
				m.Ver = []byte{}
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipTcpmsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTcpmsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *P2PMessage_Handshake) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTcpmsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Handshake: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Handshake: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubNetId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTcpmsg
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubNetId = append(m.SubNetId[:0], dAtA[iNdEx:postIndex]...)
			if m.SubNetId == nil {
				m.SubNetId = []byte{}
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTcpmsg
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeId = append(m.NodeId[:0], dAtA[iNdEx:postIndex]...)
			if m.NodeId == nil {
				m.NodeId = []byte{}
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IP", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTcpmsg
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IP = append(m.IP[:0], dAtA[iNdEx:postIndex]...)
			if m.IP == nil {
				m.IP = []byte{}
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000004)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UDP", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.UDP = &v
			hasFields[0] |= uint64(0x00000008)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TCP", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TCP = &v
			hasFields[0] |= uint64(0x00000010)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProtoNum", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ProtoNum = &v
			hasFields[0] |= uint64(0x00000020)
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Protocols", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTcpmsg
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Protocols = append(m.Protocols, &P2PMessage_Protocol{})
			if err := m.Protocols[len(m.Protocols)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignR", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SignR = &v
			hasFields[0] |= uint64(0x00000040)
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field R", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTcpmsg
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.R = append(m.R[:0], dAtA[iNdEx:postIndex]...)
			if m.R == nil {
				m.R = []byte{}
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000080)
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignS", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SignS = &v
			hasFields[0] |= uint64(0x00000100)
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field S", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTcpmsg
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.S = append(m.S[:0], dAtA[iNdEx:postIndex]...)
			if m.S == nil {
				m.S = []byte{}
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000200)
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Extra", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTcpmsg
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Extra = append(m.Extra[:0], dAtA[iNdEx:postIndex]...)
			if m.Extra == nil {
				m.Extra = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTcpmsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTcpmsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000008) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000010) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000020) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000040) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000080) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000100) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000200) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *P2PMessage_Ping) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTcpmsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Ping: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Ping: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seq", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Seq = &v
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Extra", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTcpmsg
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Extra = append(m.Extra[:0], dAtA[iNdEx:postIndex]...)
			if m.Extra == nil {
				m.Extra = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTcpmsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTcpmsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *P2PMessage_Pong) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTcpmsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Pong: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Pong: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seq", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Seq = &v
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Extra", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTcpmsg
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Extra = append(m.Extra[:0], dAtA[iNdEx:postIndex]...)
			if m.Extra == nil {
				m.Extra = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTcpmsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTcpmsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTcpmsg(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTcpmsg
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthTcpmsg
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowTcpmsg
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipTcpmsg(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthTcpmsg = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTcpmsg   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("tcpmsg.proto", fileDescriptor_tcpmsg_0e96c110557f47de) }

var fileDescriptor_tcpmsg_0e96c110557f47de = []byte{
	// 565 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcd, 0x6e, 0xd3, 0x4e,
	0x14, 0xc5, 0xeb, 0xaf, 0x34, 0xbe, 0x71, 0xf2, 0xf7, 0x7f, 0x28, 0x68, 0x94, 0x45, 0xb0, 0x2a,
	0x44, 0xad, 0x0a, 0x79, 0xe1, 0x35, 0x2c, 0xd2, 0xc4, 0x6a, 0xac, 0x34, 0xee, 0x68, 0x1c, 0xaa,
	0xee, 0x2a, 0x37, 0xb6, 0x9c, 0xa8, 0x8d, 0x1d, 0x62, 0x57, 0x6a, 0xde, 0x84, 0x47, 0x40, 0xe2,
	0x11, 0x78, 0x01, 0x96, 0x3c, 0x02, 0x0a, 0x0f, 0x02, 0x9a, 0xf1, 0x47, 0x0a, 0x2a, 0xa8, 0xbb,
	0x7b, 0x8e, 0x7e, 0x77, 0xe6, 0xcc, 0xbd, 0x03, 0x5a, 0x3e, 0x5b, 0x2d, 0xb3, 0xd8, 0x5a, 0xad,
	0xd3, 0x3c, 0x45, 0x6a, 0xa5, 0xae, 0x0f, 0xbf, 0x08, 0x00, 0xc4, 0x26, 0x24, 0x98, 0xdd, 0x04,
	0x71, 0x84, 0x8e, 0x40, 0x22, 0x8b, 0x10, 0x0b, 0x86, 0x68, 0x76, 0xec, 0xe7, 0x56, 0xcd, 0x59,
	0x84, 0x35, 0xce, 0xd2, 0x5b, 0x37, 0xa4, 0x8c, 0x40, 0x6f, 0xa0, 0xe1, 0xdc, 0xe7, 0x93, 0x45,
	0x88, 0x45, 0x43, 0x30, 0x3b, 0xf6, 0xc1, 0x03, 0x76, 0x12, 0x65, 0x59, 0x10, 0x47, 0x6e, 0x48,
	0x4b, 0x06, 0xbd, 0xe0, 0xf4, 0x38, 0xda, 0x60, 0xc9, 0x10, 0x4c, 0x8d, 0x96, 0x0a, 0xbd, 0x82,
	0x36, 0x09, 0x36, 0xb7, 0x69, 0x10, 0x9e, 0x45, 0x49, 0x9c, 0xcf, 0xb1, 0x6c, 0x88, 0x66, 0x9b,
	0xfe, 0x6e, 0x22, 0x0c, 0xfb, 0xa5, 0x81, 0x15, 0xde, 0x5e, 0xc9, 0xc3, 0x4f, 0x0a, 0x4f, 0x5f,
	0x5e, 0x88, 0x5e, 0x83, 0xb4, 0xac, 0xd3, 0x3f, 0x9e, 0x88, 0x01, 0xe8, 0x1d, 0xa8, 0xf3, 0x20,
	0x09, 0xb3, 0x79, 0x70, 0x13, 0xf1, 0xfc, 0x2d, 0xfb, 0xe5, 0xc3, 0xb7, 0xd6, 0x27, 0x5a, 0xa3,
	0x0a, 0xa3, 0xbb, 0x0e, 0x64, 0x81, 0xbc, 0x5a, 0x24, 0x31, 0x7f, 0x4b, 0xcb, 0xee, 0x3e, 0xde,
	0x49, 0x16, 0x49, 0x4c, 0x39, 0xc7, 0xf9, 0x34, 0x89, 0xb1, 0xfc, 0x4f, 0x3e, 0xe5, 0x7c, 0x9a,
	0xc4, 0x5d, 0x07, 0x9a, 0xd5, 0xb8, 0x9f, 0xbe, 0x10, 0x1d, 0xa4, 0x8b, 0x68, 0x8d, 0x45, 0x43,
	0x34, 0x35, 0xca, 0xca, 0xee, 0x67, 0x11, 0xd4, 0x3a, 0x3f, 0xea, 0x42, 0xd3, 0xbf, 0xbb, 0xf6,
	0xa2, 0xdc, 0x2d, 0x4e, 0xd3, 0x68, 0xad, 0xd9, 0x7a, 0xbc, 0x34, 0x8c, 0xdc, 0xb0, 0x6c, 0x2f,
	0x15, 0xea, 0x80, 0xe8, 0x12, 0x2c, 0x71, 0x4f, 0x74, 0x09, 0xbb, 0xe3, 0xfd, 0x90, 0x94, 0x4b,
	0x62, 0x25, 0x73, 0xa6, 0x03, 0x82, 0x95, 0xc2, 0x99, 0x0e, 0x08, 0xbb, 0x87, 0x47, 0xf3, 0xee,
	0x96, 0xb8, 0xc1, 0xed, 0x5a, 0xa3, 0xb7, 0xa0, 0x56, 0xb1, 0x33, 0xbc, 0x6f, 0x48, 0x66, 0xcb,
	0xee, 0xfd, 0x65, 0x1a, 0x25, 0x46, 0x77, 0x0d, 0xe8, 0x00, 0x14, 0x7f, 0x11, 0x27, 0x14, 0x37,
	0x0d, 0xd1, 0x54, 0x68, 0x21, 0x90, 0x06, 0x02, 0xc5, 0x2a, 0x8f, 0x28, 0xd0, 0x8a, 0xf1, 0x31,
	0xec, 0x18, 0x9f, 0x31, 0x3e, 0x6e, 0x15, 0x8c, 0xcf, 0x18, 0xe7, 0x3e, 0x5f, 0x07, 0x58, 0xe3,
	0x9f, 0xa9, 0x10, 0x5d, 0x0b, 0x64, 0xb6, 0x32, 0xf6, 0xa2, 0x2c, 0xfa, 0xc0, 0x47, 0x24, 0x53,
	0x56, 0xee, 0x78, 0xf1, 0x4f, 0x3e, 0x7d, 0x3a, 0x7f, 0x7c, 0x04, 0xb0, 0x5b, 0x19, 0x6a, 0xc1,
	0x3e, 0x71, 0x87, 0x57, 0xc4, 0x26, 0xfa, 0x1e, 0xd2, 0x0a, 0xe1, 0x5c, 0x4e, 0xf5, 0x9f, 0xc2,
	0xf1, 0x06, 0xd4, 0xfa, 0xbb, 0xa2, 0xff, 0xa1, 0x3d, 0x71, 0x87, 0x57, 0xa3, 0xbe, 0x37, 0xf4,
	0x47, 0xfd, 0xb1, 0xc3, 0xe9, 0x26, 0xb3, 0x88, 0xeb, 0x9d, 0xea, 0x42, 0xad, 0xce, 0xbd, 0x53,
	0x5d, 0x44, 0x00, 0x0d, 0xa6, 0xa6, 0x97, 0xba, 0x84, 0xda, 0xa0, 0xb2, 0xda, 0xb9, 0x70, 0xbc,
	0xa9, 0x2e, 0xa3, 0x67, 0xf0, 0x1f, 0x93, 0x27, 0x67, 0xe7, 0x83, 0xf1, 0xc8, 0xe9, 0x0f, 0x1d,
	0xaa, 0x2b, 0x15, 0xc3, 0x4d, 0xbd, 0x71, 0xa2, 0x7f, 0xdd, 0xf6, 0x84, 0x6f, 0xdb, 0x9e, 0xf0,
	0x7d, 0xdb, 0x13, 0x3e, 0xfe, 0xe8, 0xed, 0xfd, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x37, 0x4f, 0x09,
	0x56, 0x38, 0x04, 0x00, 0x00,
}
