// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block.proto

package corepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Account struct {
	// account transaction nonce start from 0
	Nonce uint64 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// account balance encoded big-endian bytes with math/big/Int.Bytes()
	Balance              []byte   `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_block_e92120e0e5e31614, []int{0}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Account) GetBalance() []byte {
	if m != nil {
		return m.Balance
	}
	return nil
}

// signature for a block header or transaction
type Signature struct {
	// signer address
	// may be omitted if address can be inferred from signature
	Signer []byte `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	// signature algorithm
	// may be omitted for default algorithm
	SigAlgorithm uint32 `protobuf:"varint,2,opt,name=sigAlgorithm,proto3" json:"sigAlgorithm,omitempty"`
	// encoded signature bytes
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_block_e92120e0e5e31614, []int{1}
}
func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (dst *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(dst, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetSigner() []byte {
	if m != nil {
		return m.Signer
	}
	return nil
}

func (m *Signature) GetSigAlgorithm() uint32 {
	if m != nil {
		return m.SigAlgorithm
	}
	return 0
}

func (m *Signature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Transaction struct {
	// chain ID
	ChainID uint32 `protobuf:"varint,1,opt,name=chainID,proto3" json:"chainID,omitempty"`
	// transaction nonce
	Nonce uint64 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// transaction from, may be omitted if inferable from signature
	From []byte `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	// transaction recipient
	Recipient []byte `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// transaction amount
	Amount []byte `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	// signature with LAST MESSAGE TAG of one byte
	Signature            *Signature `protobuf:"bytes,15,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_block_e92120e0e5e31614, []int{2}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetChainID() uint32 {
	if m != nil {
		return m.ChainID
	}
	return 0
}

func (m *Transaction) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Transaction) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Transaction) GetRecipient() []byte {
	if m != nil {
		return m.Recipient
	}
	return nil
}

func (m *Transaction) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *Transaction) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

// message for
//   block header
//   bloom filter for related addresses
//   multiple signatures from validator
type SignedBlockHeader struct {
	// embedded encoded block header
	Header []byte `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// block tx bloom filter
	Bloom []byte `protobuf:"bytes,2,opt,name=bloom,proto3" json:"bloom,omitempty"`
	// header signature for hash(hash(header) + bloom)
	Signatures           []*Signature `protobuf:"bytes,3,rep,name=signatures,proto3" json:"signatures,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SignedBlockHeader) Reset()         { *m = SignedBlockHeader{} }
func (m *SignedBlockHeader) String() string { return proto.CompactTextString(m) }
func (*SignedBlockHeader) ProtoMessage()    {}
func (*SignedBlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_block_e92120e0e5e31614, []int{3}
}
func (m *SignedBlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedBlockHeader.Unmarshal(m, b)
}
func (m *SignedBlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedBlockHeader.Marshal(b, m, deterministic)
}
func (dst *SignedBlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedBlockHeader.Merge(dst, src)
}
func (m *SignedBlockHeader) XXX_Size() int {
	return xxx_messageInfo_SignedBlockHeader.Size(m)
}
func (m *SignedBlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedBlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_SignedBlockHeader proto.InternalMessageInfo

func (m *SignedBlockHeader) GetHeader() []byte {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SignedBlockHeader) GetBloom() []byte {
	if m != nil {
		return m.Bloom
	}
	return nil
}

func (m *SignedBlockHeader) GetSignatures() []*Signature {
	if m != nil {
		return m.Signatures
	}
	return nil
}

// message for
//   block body = block - header
type BlockBody struct {
	// encoded transaction bytes
	RawTransactions      [][]byte `protobuf:"bytes,1,rep,name=raw_transactions,json=rawTransactions,proto3" json:"raw_transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockBody) Reset()         { *m = BlockBody{} }
func (m *BlockBody) String() string { return proto.CompactTextString(m) }
func (*BlockBody) ProtoMessage()    {}
func (*BlockBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_block_e92120e0e5e31614, []int{4}
}
func (m *BlockBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockBody.Unmarshal(m, b)
}
func (m *BlockBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockBody.Marshal(b, m, deterministic)
}
func (dst *BlockBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockBody.Merge(dst, src)
}
func (m *BlockBody) XXX_Size() int {
	return xxx_messageInfo_BlockBody.Size(m)
}
func (m *BlockBody) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockBody.DiscardUnknown(m)
}

var xxx_messageInfo_BlockBody proto.InternalMessageInfo

func (m *BlockBody) GetRawTransactions() [][]byte {
	if m != nil {
		return m.RawTransactions
	}
	return nil
}

type Block struct {
	Header               *SignedBlockHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *BlockBody         `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_block_e92120e0e5e31614, []int{5}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeader() *SignedBlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetBody() *BlockBody {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Account)(nil), "corepb.Account")
	proto.RegisterType((*Signature)(nil), "corepb.Signature")
	proto.RegisterType((*Transaction)(nil), "corepb.Transaction")
	proto.RegisterType((*SignedBlockHeader)(nil), "corepb.SignedBlockHeader")
	proto.RegisterType((*BlockBody)(nil), "corepb.BlockBody")
	proto.RegisterType((*Block)(nil), "corepb.Block")
}

func init() { proto.RegisterFile("block.proto", fileDescriptor_block_e92120e0e5e31614) }

var fileDescriptor_block_e92120e0e5e31614 = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4f, 0x6b, 0xc2, 0x30,
	0x1c, 0xa5, 0xb6, 0x2a, 0xfe, 0x5a, 0x71, 0x86, 0x31, 0x3a, 0xd8, 0xa1, 0x14, 0x06, 0xdd, 0xc5,
	0xa1, 0x83, 0xc1, 0x8e, 0xca, 0x0e, 0xdb, 0xb5, 0xdb, 0x7d, 0xa4, 0x69, 0x56, 0xc3, 0xda, 0x44,
	0xd2, 0x88, 0xf8, 0xcd, 0xf6, 0xf1, 0x46, 0x12, 0x5b, 0x23, 0xec, 0x96, 0xf7, 0xf4, 0xf7, 0xfe,
	0x51, 0x08, 0x8b, 0x5a, 0x90, 0x9f, 0xc5, 0x4e, 0x0a, 0x25, 0xd0, 0x88, 0x08, 0x49, 0x77, 0x45,
	0xfa, 0x02, 0xe3, 0x35, 0x21, 0x62, 0xcf, 0x15, 0xba, 0x86, 0x21, 0x17, 0x9c, 0xd0, 0xd8, 0x4b,
	0xbc, 0x2c, 0xc8, 0x2d, 0x40, 0x31, 0x8c, 0x0b, 0x5c, 0x63, 0xcd, 0x0f, 0x12, 0x2f, 0x8b, 0xf2,
	0x0e, 0xa6, 0x14, 0x26, 0x1f, 0xac, 0xe2, 0x58, 0xed, 0x25, 0x45, 0x37, 0x30, 0x6a, 0x59, 0xc5,
	0xa9, 0x34, 0xd7, 0x51, 0x7e, 0x42, 0x28, 0x85, 0xa8, 0x65, 0xd5, 0xba, 0xae, 0x84, 0x64, 0x6a,
	0xdb, 0x18, 0x8d, 0x69, 0x7e, 0xc1, 0xa1, 0x3b, 0x98, 0xb4, 0x9d, 0x50, 0xec, 0x9b, 0xf3, 0x33,
	0x91, 0xfe, 0x7a, 0x10, 0x7e, 0x4a, 0xcc, 0x5b, 0x4c, 0x14, 0x13, 0x5c, 0x07, 0x22, 0x5b, 0xcc,
	0xf8, 0xfb, 0xab, 0xb1, 0x9a, 0xe6, 0x1d, 0x3c, 0x17, 0x18, 0xb8, 0x05, 0x10, 0x04, 0xdf, 0x52,
	0x34, 0x27, 0x61, 0xf3, 0xd6, 0x8e, 0x92, 0x12, 0xb6, 0x63, 0x94, 0xab, 0x38, 0xb0, 0x8e, 0x3d,
	0xa1, 0xbb, 0xe0, 0x46, 0x4f, 0x12, 0x0f, 0x6d, 0x17, 0x8b, 0xd0, 0xa3, 0x9b, 0x73, 0x96, 0x78,
	0x59, 0xb8, 0x9a, 0x2f, 0xec, 0x8e, 0x8b, 0x7e, 0x09, 0x37, 0xba, 0x82, 0xb9, 0xe6, 0x69, 0xb9,
	0xd1, 0xcb, 0xbf, 0x51, 0x5c, 0x52, 0xa9, 0xd5, 0xb7, 0xe6, 0xd5, 0x2d, 0x65, 0x91, 0x4e, 0x5f,
	0xd4, 0x42, 0x34, 0xa7, 0x99, 0x2d, 0x40, 0x4b, 0x80, 0x5e, 0xaf, 0x8d, 0xfd, 0xc4, 0xff, 0xdf,
	0xd4, 0xf9, 0x53, 0xfa, 0x0c, 0x13, 0xe3, 0xb7, 0x11, 0xe5, 0x11, 0x3d, 0xc0, 0x95, 0xc4, 0x87,
	0x2f, 0x75, 0x1e, 0xb0, 0x8d, 0xbd, 0xc4, 0xcf, 0xa2, 0x7c, 0x26, 0xf1, 0xc1, 0xd9, 0xb5, 0x4d,
	0x31, 0x0c, 0xcd, 0x1d, 0x5a, 0x5e, 0x24, 0x0c, 0x57, 0xb7, 0xae, 0xdf, 0x45, 0x99, 0x3e, 0xfc,
	0x3d, 0x04, 0x85, 0x28, 0x8f, 0x26, 0xbb, 0x13, 0xb0, 0xcf, 0x91, 0x9b, 0x9f, 0x8b, 0x91, 0xf9,
	0xf8, 0x9e, 0xfe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xce, 0x98, 0x2c, 0x36, 0x8b, 0x02, 0x00, 0x00,
}
