// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dhtmsg.proto

package dhtmsg_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProtocolId int32

const (
	ProtocolId_PID_DHT ProtocolId = 0
	ProtocolId_PID_EXT ProtocolId = 255
)

var ProtocolId_name = map[int32]string{
	0:   "PID_DHT",
	255: "PID_EXT",
}
var ProtocolId_value = map[string]int32{
	"PID_DHT": 0,
	"PID_EXT": 255,
}

func (x ProtocolId) Enum() *ProtocolId {
	p := new(ProtocolId)
	*p = x
	return p
}
func (x ProtocolId) String() string {
	return proto.EnumName(ProtocolId_name, int32(x))
}
func (x *ProtocolId) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProtocolId_value, data, "ProtocolId")
	if err != nil {
		return err
	}
	*x = ProtocolId(value)
	return nil
}
func (ProtocolId) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dhtmsg_0fb4397fe10fcc0f, []int{0}
}

type DhtMessage_MessageType int32

const (
	DhtMessage_MID_HANDSHAKE       DhtMessage_MessageType = 0
	DhtMessage_MID_FINDNODE        DhtMessage_MessageType = 1
	DhtMessage_MID_NEIGHBORS       DhtMessage_MessageType = 2
	DhtMessage_MID_PUTVALUE        DhtMessage_MessageType = 3
	DhtMessage_MID_GETVALUE_REQ    DhtMessage_MessageType = 4
	DhtMessage_MID_GETVALUE_RSP    DhtMessage_MessageType = 5
	DhtMessage_MID_PUTPROVIDER     DhtMessage_MessageType = 6
	DhtMessage_MID_GETPROVIDER_REQ DhtMessage_MessageType = 7
	DhtMessage_MID_GETPROVIDER_RSP DhtMessage_MessageType = 8
	DhtMessage_MID_PING            DhtMessage_MessageType = 9
	DhtMessage_MID_PONG            DhtMessage_MessageType = 10
)

var DhtMessage_MessageType_name = map[int32]string{
	0:  "MID_HANDSHAKE",
	1:  "MID_FINDNODE",
	2:  "MID_NEIGHBORS",
	3:  "MID_PUTVALUE",
	4:  "MID_GETVALUE_REQ",
	5:  "MID_GETVALUE_RSP",
	6:  "MID_PUTPROVIDER",
	7:  "MID_GETPROVIDER_REQ",
	8:  "MID_GETPROVIDER_RSP",
	9:  "MID_PING",
	10: "MID_PONG",
}
var DhtMessage_MessageType_value = map[string]int32{
	"MID_HANDSHAKE":       0,
	"MID_FINDNODE":        1,
	"MID_NEIGHBORS":       2,
	"MID_PUTVALUE":        3,
	"MID_GETVALUE_REQ":    4,
	"MID_GETVALUE_RSP":    5,
	"MID_PUTPROVIDER":     6,
	"MID_GETPROVIDER_REQ": 7,
	"MID_GETPROVIDER_RSP": 8,
	"MID_PING":            9,
	"MID_PONG":            10,
}

func (x DhtMessage_MessageType) Enum() *DhtMessage_MessageType {
	p := new(DhtMessage_MessageType)
	*p = x
	return p
}
func (x DhtMessage_MessageType) String() string {
	return proto.EnumName(DhtMessage_MessageType_name, int32(x))
}
func (x *DhtMessage_MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DhtMessage_MessageType_value, data, "DhtMessage_MessageType")
	if err != nil {
		return err
	}
	*x = DhtMessage_MessageType(value)
	return nil
}
func (DhtMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dhtmsg_0fb4397fe10fcc0f, []int{1, 0}
}

type DhtMessage_ConnectionType int32

const (
	DhtMessage_CONT_NO     DhtMessage_ConnectionType = 0
	DhtMessage_CONT_YES    DhtMessage_ConnectionType = 1
	DhtMessage_CONT_MAY    DhtMessage_ConnectionType = 2
	DhtMessage_CONT_FAILED DhtMessage_ConnectionType = 3
)

var DhtMessage_ConnectionType_name = map[int32]string{
	0: "CONT_NO",
	1: "CONT_YES",
	2: "CONT_MAY",
	3: "CONT_FAILED",
}
var DhtMessage_ConnectionType_value = map[string]int32{
	"CONT_NO":     0,
	"CONT_YES":    1,
	"CONT_MAY":    2,
	"CONT_FAILED": 3,
}

func (x DhtMessage_ConnectionType) Enum() *DhtMessage_ConnectionType {
	p := new(DhtMessage_ConnectionType)
	*p = x
	return p
}
func (x DhtMessage_ConnectionType) String() string {
	return proto.EnumName(DhtMessage_ConnectionType_name, int32(x))
}
func (x *DhtMessage_ConnectionType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DhtMessage_ConnectionType_value, data, "DhtMessage_ConnectionType")
	if err != nil {
		return err
	}
	*x = DhtMessage_ConnectionType(value)
	return nil
}
func (DhtMessage_ConnectionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dhtmsg_0fb4397fe10fcc0f, []int{1, 1}
}

type DhtPackage struct {
	Pid                  *ProtocolId `protobuf:"varint,1,req,name=Pid,enum=dhtmsg.pb.ProtocolId" json:"Pid,omitempty"`
	PayloadLength        *uint32     `protobuf:"varint,2,req,name=PayloadLength" json:"PayloadLength,omitempty"`
	Payload              []byte      `protobuf:"bytes,3,opt,name=Payload" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DhtPackage) Reset()         { *m = DhtPackage{} }
func (m *DhtPackage) String() string { return proto.CompactTextString(m) }
func (*DhtPackage) ProtoMessage()    {}
func (*DhtPackage) Descriptor() ([]byte, []int) {
	return fileDescriptor_dhtmsg_0fb4397fe10fcc0f, []int{0}
}
func (m *DhtPackage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DhtPackage.Unmarshal(m, b)
}
func (m *DhtPackage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DhtPackage.Marshal(b, m, deterministic)
}
func (dst *DhtPackage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DhtPackage.Merge(dst, src)
}
func (m *DhtPackage) XXX_Size() int {
	return xxx_messageInfo_DhtPackage.Size(m)
}
func (m *DhtPackage) XXX_DiscardUnknown() {
	xxx_messageInfo_DhtPackage.DiscardUnknown(m)
}

var xxx_messageInfo_DhtPackage proto.InternalMessageInfo

func (m *DhtPackage) GetPid() ProtocolId {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ProtocolId_PID_DHT
}

func (m *DhtPackage) GetPayloadLength() uint32 {
	if m != nil && m.PayloadLength != nil {
		return *m.PayloadLength
	}
	return 0
}

func (m *DhtPackage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type DhtMessage struct {
	MsgType              *DhtMessage_MessageType    `protobuf:"varint,1,req,name=msgType,enum=dhtmsg.pb.DhtMessage_MessageType" json:"msgType,omitempty"`
	Handshake            *DhtMessage_Handshake      `protobuf:"bytes,2,opt,name=handshake" json:"handshake,omitempty"`
	FindNode             *DhtMessage_FindNode       `protobuf:"bytes,3,opt,name=findNode" json:"findNode,omitempty"`
	Neighbors            *DhtMessage_Neighbors      `protobuf:"bytes,4,opt,name=neighbors" json:"neighbors,omitempty"`
	PutValue             *DhtMessage_PutValue       `protobuf:"bytes,5,opt,name=putValue" json:"putValue,omitempty"`
	GetValueReq          *DhtMessage_GetValueReq    `protobuf:"bytes,6,opt,name=getValueReq" json:"getValueReq,omitempty"`
	GetValueRsp          *DhtMessage_GetValueRsp    `protobuf:"bytes,7,opt,name=getValueRsp" json:"getValueRsp,omitempty"`
	PutProvider          *DhtMessage_PutProvider    `protobuf:"bytes,8,opt,name=putProvider" json:"putProvider,omitempty"`
	GetProviderReq       *DhtMessage_GetProviderReq `protobuf:"bytes,9,opt,name=getProviderReq" json:"getProviderReq,omitempty"`
	GetProviderRsp       *DhtMessage_GetProviderRsp `protobuf:"bytes,10,opt,name=getProviderRsp" json:"getProviderRsp,omitempty"`
	Ping                 *DhtMessage_Ping           `protobuf:"bytes,11,opt,name=ping" json:"ping,omitempty"`
	Pong                 *DhtMessage_Pong           `protobuf:"bytes,12,opt,name=pong" json:"pong,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *DhtMessage) Reset()         { *m = DhtMessage{} }
func (m *DhtMessage) String() string { return proto.CompactTextString(m) }
func (*DhtMessage) ProtoMessage()    {}
func (*DhtMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_dhtmsg_0fb4397fe10fcc0f, []int{1}
}
func (m *DhtMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DhtMessage.Unmarshal(m, b)
}
func (m *DhtMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DhtMessage.Marshal(b, m, deterministic)
}
func (dst *DhtMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DhtMessage.Merge(dst, src)
}
func (m *DhtMessage) XXX_Size() int {
	return xxx_messageInfo_DhtMessage.Size(m)
}
func (m *DhtMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DhtMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DhtMessage proto.InternalMessageInfo

func (m *DhtMessage) GetMsgType() DhtMessage_MessageType {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return DhtMessage_MID_HANDSHAKE
}

func (m *DhtMessage) GetHandshake() *DhtMessage_Handshake {
	if m != nil {
		return m.Handshake
	}
	return nil
}

func (m *DhtMessage) GetFindNode() *DhtMessage_FindNode {
	if m != nil {
		return m.FindNode
	}
	return nil
}

func (m *DhtMessage) GetNeighbors() *DhtMessage_Neighbors {
	if m != nil {
		return m.Neighbors
	}
	return nil
}

func (m *DhtMessage) GetPutValue() *DhtMessage_PutValue {
	if m != nil {
		return m.PutValue
	}
	return nil
}

func (m *DhtMessage) GetGetValueReq() *DhtMessage_GetValueReq {
	if m != nil {
		return m.GetValueReq
	}
	return nil
}

func (m *DhtMessage) GetGetValueRsp() *DhtMessage_GetValueRsp {
	if m != nil {
		return m.GetValueRsp
	}
	return nil
}

func (m *DhtMessage) GetPutProvider() *DhtMessage_PutProvider {
	if m != nil {
		return m.PutProvider
	}
	return nil
}

func (m *DhtMessage) GetGetProviderReq() *DhtMessage_GetProviderReq {
	if m != nil {
		return m.GetProviderReq
	}
	return nil
}

func (m *DhtMessage) GetGetProviderRsp() *DhtMessage_GetProviderRsp {
	if m != nil {
		return m.GetProviderRsp
	}
	return nil
}

func (m *DhtMessage) GetPing() *DhtMessage_Ping {
	if m != nil {
		return m.Ping
	}
	return nil
}

func (m *DhtMessage) GetPong() *DhtMessage_Pong {
	if m != nil {
		return m.Pong
	}
	return nil
}

type DhtMessage_Node struct {
	IP                   []byte                     `protobuf:"bytes,1,req,name=IP" json:"IP,omitempty"`
	UDP                  *uint32                    `protobuf:"varint,2,req,name=UDP" json:"UDP,omitempty"`
	TCP                  *uint32                    `protobuf:"varint,3,req,name=TCP" json:"TCP,omitempty"`
	NodeId               []byte                     `protobuf:"bytes,4,req,name=NodeId" json:"NodeId,omitempty"`
	ConnType             *DhtMessage_ConnectionType `protobuf:"varint,5,req,name=ConnType,enum=dhtmsg.pb.DhtMessage_ConnectionType" json:"ConnType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *DhtMessage_Node) Reset()         { *m = DhtMessage_Node{} }
func (m *DhtMessage_Node) String() string { return proto.CompactTextString(m) }
func (*DhtMessage_Node) ProtoMessage()    {}
func (*DhtMessage_Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_dhtmsg_0fb4397fe10fcc0f, []int{1, 0}
}
func (m *DhtMessage_Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DhtMessage_Node.Unmarshal(m, b)
}
func (m *DhtMessage_Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DhtMessage_Node.Marshal(b, m, deterministic)
}
func (dst *DhtMessage_Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DhtMessage_Node.Merge(dst, src)
}
func (m *DhtMessage_Node) XXX_Size() int {
	return xxx_messageInfo_DhtMessage_Node.Size(m)
}
func (m *DhtMessage_Node) XXX_DiscardUnknown() {
	xxx_messageInfo_DhtMessage_Node.DiscardUnknown(m)
}

var xxx_messageInfo_DhtMessage_Node proto.InternalMessageInfo

func (m *DhtMessage_Node) GetIP() []byte {
	if m != nil {
		return m.IP
	}
	return nil
}

func (m *DhtMessage_Node) GetUDP() uint32 {
	if m != nil && m.UDP != nil {
		return *m.UDP
	}
	return 0
}

func (m *DhtMessage_Node) GetTCP() uint32 {
	if m != nil && m.TCP != nil {
		return *m.TCP
	}
	return 0
}

func (m *DhtMessage_Node) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *DhtMessage_Node) GetConnType() DhtMessage_ConnectionType {
	if m != nil && m.ConnType != nil {
		return *m.ConnType
	}
	return DhtMessage_CONT_NO
}

type DhtMessage_Value struct {
	Key                  []byte   `protobuf:"bytes,1,req,name=Key" json:"Key,omitempty"`
	Val                  []byte   `protobuf:"bytes,2,req,name=Val" json:"Val,omitempty"`
	Extra                []byte   `protobuf:"bytes,3,opt,name=Extra" json:"Extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DhtMessage_Value) Reset()         { *m = DhtMessage_Value{} }
func (m *DhtMessage_Value) String() string { return proto.CompactTextString(m) }
func (*DhtMessage_Value) ProtoMessage()    {}
func (*DhtMessage_Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_dhtmsg_0fb4397fe10fcc0f, []int{1, 1}
}
func (m *DhtMessage_Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DhtMessage_Value.Unmarshal(m, b)
}
func (m *DhtMessage_Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DhtMessage_Value.Marshal(b, m, deterministic)
}
func (dst *DhtMessage_Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DhtMessage_Value.Merge(dst, src)
}
func (m *DhtMessage_Value) XXX_Size() int {
	return xxx_messageInfo_DhtMessage_Value.Size(m)
}
func (m *DhtMessage_Value) XXX_DiscardUnknown() {
	xxx_messageInfo_DhtMessage_Value.DiscardUnknown(m)
}

var xxx_messageInfo_DhtMessage_Value proto.InternalMessageInfo

func (m *DhtMessage_Value) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *DhtMessage_Value) GetVal() []byte {
	if m != nil {
		return m.Val
	}
	return nil
}

func (m *DhtMessage_Value) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

type DhtMessage_Provider struct {
	Key                  []byte             `protobuf:"bytes,1,req,name=Key" json:"Key,omitempty"`
	Nodes                []*DhtMessage_Node `protobuf:"bytes,2,rep,name=Nodes" json:"Nodes,omitempty"`
	Extra                []byte             `protobuf:"bytes,3,opt,name=Extra" json:"Extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DhtMessage_Provider) Reset()         { *m = DhtMessage_Provider{} }
func (m *DhtMessage_Provider) String() string { return proto.CompactTextString(m) }
func (*DhtMessage_Provider) ProtoMessage()    {}
func (*DhtMessage_Provider) Descriptor() ([]byte, []int) {
	return fileDescriptor_dhtmsg_0fb4397fe10fcc0f, []int{1, 2}
}
func (m *DhtMessage_Provider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DhtMessage_Provider.Unmarshal(m, b)
}
func (m *DhtMessage_Provider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DhtMessage_Provider.Marshal(b, m, deterministic)
}
func (dst *DhtMessage_Provider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DhtMessage_Provider.Merge(dst, src)
}
func (m *DhtMessage_Provider) XXX_Size() int {
	return xxx_messageInfo_DhtMessage_Provider.Size(m)
}
func (m *DhtMessage_Provider) XXX_DiscardUnknown() {
	xxx_messageInfo_DhtMessage_Provider.DiscardUnknown(m)
}

var xxx_messageInfo_DhtMessage_Provider proto.InternalMessageInfo

func (m *DhtMessage_Provider) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *DhtMessage_Provider) GetNodes() []*DhtMessage_Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *DhtMessage_Provider) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

type DhtMessage_Protocol struct {
	Pid                  *ProtocolId `protobuf:"varint,1,req,name=Pid,enum=dhtmsg.pb.ProtocolId" json:"Pid,omitempty"`
	Ver                  []byte      `protobuf:"bytes,2,req,name=Ver" json:"Ver,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DhtMessage_Protocol) Reset()         { *m = DhtMessage_Protocol{} }
func (m *DhtMessage_Protocol) String() string { return proto.CompactTextString(m) }
func (*DhtMessage_Protocol) ProtoMessage()    {}
func (*DhtMessage_Protocol) Descriptor() ([]byte, []int) {
	return fileDescriptor_dhtmsg_0fb4397fe10fcc0f, []int{1, 3}
}
func (m *DhtMessage_Protocol) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DhtMessage_Protocol.Unmarshal(m, b)
}
func (m *DhtMessage_Protocol) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DhtMessage_Protocol.Marshal(b, m, deterministic)
}
func (dst *DhtMessage_Protocol) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DhtMessage_Protocol.Merge(dst, src)
}
func (m *DhtMessage_Protocol) XXX_Size() int {
	return xxx_messageInfo_DhtMessage_Protocol.Size(m)
}
func (m *DhtMessage_Protocol) XXX_DiscardUnknown() {
	xxx_messageInfo_DhtMessage_Protocol.DiscardUnknown(m)
}

var xxx_messageInfo_DhtMessage_Protocol proto.InternalMessageInfo

func (m *DhtMessage_Protocol) GetPid() ProtocolId {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ProtocolId_PID_DHT
}

func (m *DhtMessage_Protocol) GetVer() []byte {
	if m != nil {
		return m.Ver
	}
	return nil
}

type DhtMessage_Handshake struct {
	Dir                  *int32                 `protobuf:"varint,1,req,name=Dir" json:"Dir,omitempty"`
	NodeId               []byte                 `protobuf:"bytes,2,req,name=NodeId" json:"NodeId,omitempty"`
	IP                   []byte                 `protobuf:"bytes,3,req,name=IP" json:"IP,omitempty"`
	UDP                  *uint32                `protobuf:"varint,4,req,name=UDP" json:"UDP,omitempty"`
	TCP                  *uint32                `protobuf:"varint,5,req,name=TCP" json:"TCP,omitempty"`
	ProtoNum             *uint32                `protobuf:"varint,6,req,name=ProtoNum" json:"ProtoNum,omitempty"`
	Protocols            []*DhtMessage_Protocol `protobuf:"bytes,7,rep,name=Protocols" json:"Protocols,omitempty"`
	Id                   *uint64                `protobuf:"varint,8,req,name=Id" json:"Id,omitempty"`
	Extra                []byte                 `protobuf:"bytes,9,opt,name=Extra" json:"Extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DhtMessage_Handshake) Reset()         { *m = DhtMessage_Handshake{} }
func (m *DhtMessage_Handshake) String() string { return proto.CompactTextString(m) }
func (*DhtMessage_Handshake) ProtoMessage()    {}
func (*DhtMessage_Handshake) Descriptor() ([]byte, []int) {
	return fileDescriptor_dhtmsg_0fb4397fe10fcc0f, []int{1, 4}
}
func (m *DhtMessage_Handshake) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DhtMessage_Handshake.Unmarshal(m, b)
}
func (m *DhtMessage_Handshake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DhtMessage_Handshake.Marshal(b, m, deterministic)
}
func (dst *DhtMessage_Handshake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DhtMessage_Handshake.Merge(dst, src)
}
func (m *DhtMessage_Handshake) XXX_Size() int {
	return xxx_messageInfo_DhtMessage_Handshake.Size(m)
}
func (m *DhtMessage_Handshake) XXX_DiscardUnknown() {
	xxx_messageInfo_DhtMessage_Handshake.DiscardUnknown(m)
}

var xxx_messageInfo_DhtMessage_Handshake proto.InternalMessageInfo

func (m *DhtMessage_Handshake) GetDir() int32 {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return 0
}

func (m *DhtMessage_Handshake) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *DhtMessage_Handshake) GetIP() []byte {
	if m != nil {
		return m.IP
	}
	return nil
}

func (m *DhtMessage_Handshake) GetUDP() uint32 {
	if m != nil && m.UDP != nil {
		return *m.UDP
	}
	return 0
}

func (m *DhtMessage_Handshake) GetTCP() uint32 {
	if m != nil && m.TCP != nil {
		return *m.TCP
	}
	return 0
}

func (m *DhtMessage_Handshake) GetProtoNum() uint32 {
	if m != nil && m.ProtoNum != nil {
		return *m.ProtoNum
	}
	return 0
}

func (m *DhtMessage_Handshake) GetProtocols() []*DhtMessage_Protocol {
	if m != nil {
		return m.Protocols
	}
	return nil
}

func (m *DhtMessage_Handshake) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *DhtMessage_Handshake) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

type DhtMessage_FindNode struct {
	From                 *DhtMessage_Node `protobuf:"bytes,1,req,name=From" json:"From,omitempty"`
	To                   *DhtMessage_Node `protobuf:"bytes,2,req,name=To" json:"To,omitempty"`
	Target               []byte           `protobuf:"bytes,3,req,name=Target" json:"Target,omitempty"`
	Id                   *uint64          `protobuf:"varint,4,req,name=Id" json:"Id,omitempty"`
	Extra                []byte           `protobuf:"bytes,5,opt,name=Extra" json:"Extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DhtMessage_FindNode) Reset()         { *m = DhtMessage_FindNode{} }
func (m *DhtMessage_FindNode) String() string { return proto.CompactTextString(m) }
func (*DhtMessage_FindNode) ProtoMessage()    {}
func (*DhtMessage_FindNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_dhtmsg_0fb4397fe10fcc0f, []int{1, 5}
}
func (m *DhtMessage_FindNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DhtMessage_FindNode.Unmarshal(m, b)
}
func (m *DhtMessage_FindNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DhtMessage_FindNode.Marshal(b, m, deterministic)
}
func (dst *DhtMessage_FindNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DhtMessage_FindNode.Merge(dst, src)
}
func (m *DhtMessage_FindNode) XXX_Size() int {
	return xxx_messageInfo_DhtMessage_FindNode.Size(m)
}
func (m *DhtMessage_FindNode) XXX_DiscardUnknown() {
	xxx_messageInfo_DhtMessage_FindNode.DiscardUnknown(m)
}

var xxx_messageInfo_DhtMessage_FindNode proto.InternalMessageInfo

func (m *DhtMessage_FindNode) GetFrom() *DhtMessage_Node {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *DhtMessage_FindNode) GetTo() *DhtMessage_Node {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *DhtMessage_FindNode) GetTarget() []byte {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *DhtMessage_FindNode) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *DhtMessage_FindNode) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

type DhtMessage_Neighbors struct {
	From                 *DhtMessage_Node   `protobuf:"bytes,1,req,name=From" json:"From,omitempty"`
	To                   *DhtMessage_Node   `protobuf:"bytes,2,req,name=To" json:"To,omitempty"`
	Nodes                []*DhtMessage_Node `protobuf:"bytes,3,rep,name=Nodes" json:"Nodes,omitempty"`
	Id                   *uint64            `protobuf:"varint,4,req,name=Id" json:"Id,omitempty"`
	Extra                []byte             `protobuf:"bytes,5,opt,name=Extra" json:"Extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DhtMessage_Neighbors) Reset()         { *m = DhtMessage_Neighbors{} }
func (m *DhtMessage_Neighbors) String() string { return proto.CompactTextString(m) }
func (*DhtMessage_Neighbors) ProtoMessage()    {}
func (*DhtMessage_Neighbors) Descriptor() ([]byte, []int) {
	return fileDescriptor_dhtmsg_0fb4397fe10fcc0f, []int{1, 6}
}
func (m *DhtMessage_Neighbors) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DhtMessage_Neighbors.Unmarshal(m, b)
}
func (m *DhtMessage_Neighbors) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DhtMessage_Neighbors.Marshal(b, m, deterministic)
}
func (dst *DhtMessage_Neighbors) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DhtMessage_Neighbors.Merge(dst, src)
}
func (m *DhtMessage_Neighbors) XXX_Size() int {
	return xxx_messageInfo_DhtMessage_Neighbors.Size(m)
}
func (m *DhtMessage_Neighbors) XXX_DiscardUnknown() {
	xxx_messageInfo_DhtMessage_Neighbors.DiscardUnknown(m)
}

var xxx_messageInfo_DhtMessage_Neighbors proto.InternalMessageInfo

func (m *DhtMessage_Neighbors) GetFrom() *DhtMessage_Node {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *DhtMessage_Neighbors) GetTo() *DhtMessage_Node {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *DhtMessage_Neighbors) GetNodes() []*DhtMessage_Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *DhtMessage_Neighbors) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *DhtMessage_Neighbors) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

type DhtMessage_PutValue struct {
	From                 *DhtMessage_Node    `protobuf:"bytes,1,req,name=From" json:"From,omitempty"`
	To                   *DhtMessage_Node    `protobuf:"bytes,2,req,name=To" json:"To,omitempty"`
	Values               []*DhtMessage_Value `protobuf:"bytes,3,rep,name=Values" json:"Values,omitempty"`
	Id                   *uint64             `protobuf:"varint,4,req,name=Id" json:"Id,omitempty"`
	Extra                []byte              `protobuf:"bytes,5,opt,name=Extra" json:"Extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *DhtMessage_PutValue) Reset()         { *m = DhtMessage_PutValue{} }
func (m *DhtMessage_PutValue) String() string { return proto.CompactTextString(m) }
func (*DhtMessage_PutValue) ProtoMessage()    {}
func (*DhtMessage_PutValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_dhtmsg_0fb4397fe10fcc0f, []int{1, 7}
}
func (m *DhtMessage_PutValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DhtMessage_PutValue.Unmarshal(m, b)
}
func (m *DhtMessage_PutValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DhtMessage_PutValue.Marshal(b, m, deterministic)
}
func (dst *DhtMessage_PutValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DhtMessage_PutValue.Merge(dst, src)
}
func (m *DhtMessage_PutValue) XXX_Size() int {
	return xxx_messageInfo_DhtMessage_PutValue.Size(m)
}
func (m *DhtMessage_PutValue) XXX_DiscardUnknown() {
	xxx_messageInfo_DhtMessage_PutValue.DiscardUnknown(m)
}

var xxx_messageInfo_DhtMessage_PutValue proto.InternalMessageInfo

func (m *DhtMessage_PutValue) GetFrom() *DhtMessage_Node {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *DhtMessage_PutValue) GetTo() *DhtMessage_Node {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *DhtMessage_PutValue) GetValues() []*DhtMessage_Value {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *DhtMessage_PutValue) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *DhtMessage_PutValue) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

type DhtMessage_GetValueReq struct {
	From                 *DhtMessage_Node `protobuf:"bytes,1,req,name=From" json:"From,omitempty"`
	To                   *DhtMessage_Node `protobuf:"bytes,2,req,name=To" json:"To,omitempty"`
	Key                  []byte           `protobuf:"bytes,3,req,name=Key" json:"Key,omitempty"`
	Id                   *uint64          `protobuf:"varint,4,req,name=Id" json:"Id,omitempty"`
	Extra                []byte           `protobuf:"bytes,5,opt,name=Extra" json:"Extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DhtMessage_GetValueReq) Reset()         { *m = DhtMessage_GetValueReq{} }
func (m *DhtMessage_GetValueReq) String() string { return proto.CompactTextString(m) }
func (*DhtMessage_GetValueReq) ProtoMessage()    {}
func (*DhtMessage_GetValueReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_dhtmsg_0fb4397fe10fcc0f, []int{1, 8}
}
func (m *DhtMessage_GetValueReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DhtMessage_GetValueReq.Unmarshal(m, b)
}
func (m *DhtMessage_GetValueReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DhtMessage_GetValueReq.Marshal(b, m, deterministic)
}
func (dst *DhtMessage_GetValueReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DhtMessage_GetValueReq.Merge(dst, src)
}
func (m *DhtMessage_GetValueReq) XXX_Size() int {
	return xxx_messageInfo_DhtMessage_GetValueReq.Size(m)
}
func (m *DhtMessage_GetValueReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DhtMessage_GetValueReq.DiscardUnknown(m)
}

var xxx_messageInfo_DhtMessage_GetValueReq proto.InternalMessageInfo

func (m *DhtMessage_GetValueReq) GetFrom() *DhtMessage_Node {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *DhtMessage_GetValueReq) GetTo() *DhtMessage_Node {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *DhtMessage_GetValueReq) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *DhtMessage_GetValueReq) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *DhtMessage_GetValueReq) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

type DhtMessage_GetValueRsp struct {
	From                 *DhtMessage_Node  `protobuf:"bytes,1,req,name=From" json:"From,omitempty"`
	To                   *DhtMessage_Node  `protobuf:"bytes,2,req,name=To" json:"To,omitempty"`
	Value                *DhtMessage_Value `protobuf:"bytes,3,opt,name=Value" json:"Value,omitempty"`
	Nodes                *DhtMessage_Node  `protobuf:"bytes,4,opt,name=Nodes" json:"Nodes,omitempty"`
	Id                   *uint64           `protobuf:"varint,5,req,name=Id" json:"Id,omitempty"`
	Extra                []byte            `protobuf:"bytes,6,opt,name=Extra" json:"Extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DhtMessage_GetValueRsp) Reset()         { *m = DhtMessage_GetValueRsp{} }
func (m *DhtMessage_GetValueRsp) String() string { return proto.CompactTextString(m) }
func (*DhtMessage_GetValueRsp) ProtoMessage()    {}
func (*DhtMessage_GetValueRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_dhtmsg_0fb4397fe10fcc0f, []int{1, 9}
}
func (m *DhtMessage_GetValueRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DhtMessage_GetValueRsp.Unmarshal(m, b)
}
func (m *DhtMessage_GetValueRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DhtMessage_GetValueRsp.Marshal(b, m, deterministic)
}
func (dst *DhtMessage_GetValueRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DhtMessage_GetValueRsp.Merge(dst, src)
}
func (m *DhtMessage_GetValueRsp) XXX_Size() int {
	return xxx_messageInfo_DhtMessage_GetValueRsp.Size(m)
}
func (m *DhtMessage_GetValueRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DhtMessage_GetValueRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DhtMessage_GetValueRsp proto.InternalMessageInfo

func (m *DhtMessage_GetValueRsp) GetFrom() *DhtMessage_Node {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *DhtMessage_GetValueRsp) GetTo() *DhtMessage_Node {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *DhtMessage_GetValueRsp) GetValue() *DhtMessage_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *DhtMessage_GetValueRsp) GetNodes() *DhtMessage_Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *DhtMessage_GetValueRsp) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *DhtMessage_GetValueRsp) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

type DhtMessage_PutProvider struct {
	From                 *DhtMessage_Node     `protobuf:"bytes,1,req,name=From" json:"From,omitempty"`
	To                   *DhtMessage_Node     `protobuf:"bytes,2,req,name=To" json:"To,omitempty"`
	Provider             *DhtMessage_Provider `protobuf:"bytes,3,req,name=Provider" json:"Provider,omitempty"`
	Id                   *uint64              `protobuf:"varint,4,req,name=Id" json:"Id,omitempty"`
	Extra                []byte               `protobuf:"bytes,5,opt,name=Extra" json:"Extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DhtMessage_PutProvider) Reset()         { *m = DhtMessage_PutProvider{} }
func (m *DhtMessage_PutProvider) String() string { return proto.CompactTextString(m) }
func (*DhtMessage_PutProvider) ProtoMessage()    {}
func (*DhtMessage_PutProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_dhtmsg_0fb4397fe10fcc0f, []int{1, 10}
}
func (m *DhtMessage_PutProvider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DhtMessage_PutProvider.Unmarshal(m, b)
}
func (m *DhtMessage_PutProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DhtMessage_PutProvider.Marshal(b, m, deterministic)
}
func (dst *DhtMessage_PutProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DhtMessage_PutProvider.Merge(dst, src)
}
func (m *DhtMessage_PutProvider) XXX_Size() int {
	return xxx_messageInfo_DhtMessage_PutProvider.Size(m)
}
func (m *DhtMessage_PutProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_DhtMessage_PutProvider.DiscardUnknown(m)
}

var xxx_messageInfo_DhtMessage_PutProvider proto.InternalMessageInfo

func (m *DhtMessage_PutProvider) GetFrom() *DhtMessage_Node {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *DhtMessage_PutProvider) GetTo() *DhtMessage_Node {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *DhtMessage_PutProvider) GetProvider() *DhtMessage_Provider {
	if m != nil {
		return m.Provider
	}
	return nil
}

func (m *DhtMessage_PutProvider) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *DhtMessage_PutProvider) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

type DhtMessage_GetProviderReq struct {
	From                 *DhtMessage_Node `protobuf:"bytes,1,req,name=From" json:"From,omitempty"`
	To                   *DhtMessage_Node `protobuf:"bytes,2,req,name=To" json:"To,omitempty"`
	Key                  []byte           `protobuf:"bytes,3,req,name=Key" json:"Key,omitempty"`
	Id                   *uint64          `protobuf:"varint,4,req,name=Id" json:"Id,omitempty"`
	Extra                []byte           `protobuf:"bytes,5,opt,name=Extra" json:"Extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DhtMessage_GetProviderReq) Reset()         { *m = DhtMessage_GetProviderReq{} }
func (m *DhtMessage_GetProviderReq) String() string { return proto.CompactTextString(m) }
func (*DhtMessage_GetProviderReq) ProtoMessage()    {}
func (*DhtMessage_GetProviderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_dhtmsg_0fb4397fe10fcc0f, []int{1, 11}
}
func (m *DhtMessage_GetProviderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DhtMessage_GetProviderReq.Unmarshal(m, b)
}
func (m *DhtMessage_GetProviderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DhtMessage_GetProviderReq.Marshal(b, m, deterministic)
}
func (dst *DhtMessage_GetProviderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DhtMessage_GetProviderReq.Merge(dst, src)
}
func (m *DhtMessage_GetProviderReq) XXX_Size() int {
	return xxx_messageInfo_DhtMessage_GetProviderReq.Size(m)
}
func (m *DhtMessage_GetProviderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DhtMessage_GetProviderReq.DiscardUnknown(m)
}

var xxx_messageInfo_DhtMessage_GetProviderReq proto.InternalMessageInfo

func (m *DhtMessage_GetProviderReq) GetFrom() *DhtMessage_Node {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *DhtMessage_GetProviderReq) GetTo() *DhtMessage_Node {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *DhtMessage_GetProviderReq) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *DhtMessage_GetProviderReq) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *DhtMessage_GetProviderReq) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

type DhtMessage_GetProviderRsp struct {
	From                 *DhtMessage_Node     `protobuf:"bytes,1,req,name=From" json:"From,omitempty"`
	To                   *DhtMessage_Node     `protobuf:"bytes,2,req,name=To" json:"To,omitempty"`
	Provider             *DhtMessage_Provider `protobuf:"bytes,3,req,name=Provider" json:"Provider,omitempty"`
	Key                  []byte               `protobuf:"bytes,4,req,name=Key" json:"Key,omitempty"`
	Nodes                []*DhtMessage_Node   `protobuf:"bytes,5,rep,name=Nodes" json:"Nodes,omitempty"`
	Id                   *uint64              `protobuf:"varint,6,req,name=Id" json:"Id,omitempty"`
	Extra                []byte               `protobuf:"bytes,7,opt,name=Extra" json:"Extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DhtMessage_GetProviderRsp) Reset()         { *m = DhtMessage_GetProviderRsp{} }
func (m *DhtMessage_GetProviderRsp) String() string { return proto.CompactTextString(m) }
func (*DhtMessage_GetProviderRsp) ProtoMessage()    {}
func (*DhtMessage_GetProviderRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_dhtmsg_0fb4397fe10fcc0f, []int{1, 12}
}
func (m *DhtMessage_GetProviderRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DhtMessage_GetProviderRsp.Unmarshal(m, b)
}
func (m *DhtMessage_GetProviderRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DhtMessage_GetProviderRsp.Marshal(b, m, deterministic)
}
func (dst *DhtMessage_GetProviderRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DhtMessage_GetProviderRsp.Merge(dst, src)
}
func (m *DhtMessage_GetProviderRsp) XXX_Size() int {
	return xxx_messageInfo_DhtMessage_GetProviderRsp.Size(m)
}
func (m *DhtMessage_GetProviderRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DhtMessage_GetProviderRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DhtMessage_GetProviderRsp proto.InternalMessageInfo

func (m *DhtMessage_GetProviderRsp) GetFrom() *DhtMessage_Node {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *DhtMessage_GetProviderRsp) GetTo() *DhtMessage_Node {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *DhtMessage_GetProviderRsp) GetProvider() *DhtMessage_Provider {
	if m != nil {
		return m.Provider
	}
	return nil
}

func (m *DhtMessage_GetProviderRsp) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *DhtMessage_GetProviderRsp) GetNodes() []*DhtMessage_Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *DhtMessage_GetProviderRsp) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *DhtMessage_GetProviderRsp) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

type DhtMessage_Ping struct {
	From                 *DhtMessage_Node `protobuf:"bytes,1,req,name=From" json:"From,omitempty"`
	To                   *DhtMessage_Node `protobuf:"bytes,2,req,name=To" json:"To,omitempty"`
	Seq                  *uint64          `protobuf:"varint,3,req,name=Seq" json:"Seq,omitempty"`
	Extra                []byte           `protobuf:"bytes,4,opt,name=Extra" json:"Extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DhtMessage_Ping) Reset()         { *m = DhtMessage_Ping{} }
func (m *DhtMessage_Ping) String() string { return proto.CompactTextString(m) }
func (*DhtMessage_Ping) ProtoMessage()    {}
func (*DhtMessage_Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_dhtmsg_0fb4397fe10fcc0f, []int{1, 13}
}
func (m *DhtMessage_Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DhtMessage_Ping.Unmarshal(m, b)
}
func (m *DhtMessage_Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DhtMessage_Ping.Marshal(b, m, deterministic)
}
func (dst *DhtMessage_Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DhtMessage_Ping.Merge(dst, src)
}
func (m *DhtMessage_Ping) XXX_Size() int {
	return xxx_messageInfo_DhtMessage_Ping.Size(m)
}
func (m *DhtMessage_Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_DhtMessage_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_DhtMessage_Ping proto.InternalMessageInfo

func (m *DhtMessage_Ping) GetFrom() *DhtMessage_Node {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *DhtMessage_Ping) GetTo() *DhtMessage_Node {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *DhtMessage_Ping) GetSeq() uint64 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

func (m *DhtMessage_Ping) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

type DhtMessage_Pong struct {
	From                 *DhtMessage_Node `protobuf:"bytes,1,req,name=From" json:"From,omitempty"`
	To                   *DhtMessage_Node `protobuf:"bytes,2,req,name=To" json:"To,omitempty"`
	Seq                  *uint64          `protobuf:"varint,3,req,name=Seq" json:"Seq,omitempty"`
	Extra                []byte           `protobuf:"bytes,4,opt,name=Extra" json:"Extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DhtMessage_Pong) Reset()         { *m = DhtMessage_Pong{} }
func (m *DhtMessage_Pong) String() string { return proto.CompactTextString(m) }
func (*DhtMessage_Pong) ProtoMessage()    {}
func (*DhtMessage_Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_dhtmsg_0fb4397fe10fcc0f, []int{1, 14}
}
func (m *DhtMessage_Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DhtMessage_Pong.Unmarshal(m, b)
}
func (m *DhtMessage_Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DhtMessage_Pong.Marshal(b, m, deterministic)
}
func (dst *DhtMessage_Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DhtMessage_Pong.Merge(dst, src)
}
func (m *DhtMessage_Pong) XXX_Size() int {
	return xxx_messageInfo_DhtMessage_Pong.Size(m)
}
func (m *DhtMessage_Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_DhtMessage_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_DhtMessage_Pong proto.InternalMessageInfo

func (m *DhtMessage_Pong) GetFrom() *DhtMessage_Node {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *DhtMessage_Pong) GetTo() *DhtMessage_Node {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *DhtMessage_Pong) GetSeq() uint64 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

func (m *DhtMessage_Pong) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

type DhtRecord struct {
	Key                  []byte   `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	Extra                []byte   `protobuf:"bytes,3,opt,name=Extra" json:"Extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DhtRecord) Reset()         { *m = DhtRecord{} }
func (m *DhtRecord) String() string { return proto.CompactTextString(m) }
func (*DhtRecord) ProtoMessage()    {}
func (*DhtRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_dhtmsg_0fb4397fe10fcc0f, []int{2}
}
func (m *DhtRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DhtRecord.Unmarshal(m, b)
}
func (m *DhtRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DhtRecord.Marshal(b, m, deterministic)
}
func (dst *DhtRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DhtRecord.Merge(dst, src)
}
func (m *DhtRecord) XXX_Size() int {
	return xxx_messageInfo_DhtRecord.Size(m)
}
func (m *DhtRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_DhtRecord.DiscardUnknown(m)
}

var xxx_messageInfo_DhtRecord proto.InternalMessageInfo

func (m *DhtRecord) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *DhtRecord) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *DhtRecord) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

type DhtProviderRecord struct {
	Key                  []byte                        `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Providers            []*DhtProviderRecord_Provider `protobuf:"bytes,2,rep,name=providers" json:"providers,omitempty"`
	Extra                []byte                        `protobuf:"bytes,3,opt,name=Extra" json:"Extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *DhtProviderRecord) Reset()         { *m = DhtProviderRecord{} }
func (m *DhtProviderRecord) String() string { return proto.CompactTextString(m) }
func (*DhtProviderRecord) ProtoMessage()    {}
func (*DhtProviderRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_dhtmsg_0fb4397fe10fcc0f, []int{3}
}
func (m *DhtProviderRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DhtProviderRecord.Unmarshal(m, b)
}
func (m *DhtProviderRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DhtProviderRecord.Marshal(b, m, deterministic)
}
func (dst *DhtProviderRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DhtProviderRecord.Merge(dst, src)
}
func (m *DhtProviderRecord) XXX_Size() int {
	return xxx_messageInfo_DhtProviderRecord.Size(m)
}
func (m *DhtProviderRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_DhtProviderRecord.DiscardUnknown(m)
}

var xxx_messageInfo_DhtProviderRecord proto.InternalMessageInfo

func (m *DhtProviderRecord) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *DhtProviderRecord) GetProviders() []*DhtProviderRecord_Provider {
	if m != nil {
		return m.Providers
	}
	return nil
}

func (m *DhtProviderRecord) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

type DhtProviderRecord_Node struct {
	IP                   []byte   `protobuf:"bytes,1,req,name=IP" json:"IP,omitempty"`
	UDP                  *uint32  `protobuf:"varint,2,req,name=UDP" json:"UDP,omitempty"`
	TCP                  *uint32  `protobuf:"varint,3,req,name=TCP" json:"TCP,omitempty"`
	NodeId               []byte   `protobuf:"bytes,4,req,name=NodeId" json:"NodeId,omitempty"`
	Extra                []byte   `protobuf:"bytes,5,opt,name=Extra" json:"Extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DhtProviderRecord_Node) Reset()         { *m = DhtProviderRecord_Node{} }
func (m *DhtProviderRecord_Node) String() string { return proto.CompactTextString(m) }
func (*DhtProviderRecord_Node) ProtoMessage()    {}
func (*DhtProviderRecord_Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_dhtmsg_0fb4397fe10fcc0f, []int{3, 0}
}
func (m *DhtProviderRecord_Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DhtProviderRecord_Node.Unmarshal(m, b)
}
func (m *DhtProviderRecord_Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DhtProviderRecord_Node.Marshal(b, m, deterministic)
}
func (dst *DhtProviderRecord_Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DhtProviderRecord_Node.Merge(dst, src)
}
func (m *DhtProviderRecord_Node) XXX_Size() int {
	return xxx_messageInfo_DhtProviderRecord_Node.Size(m)
}
func (m *DhtProviderRecord_Node) XXX_DiscardUnknown() {
	xxx_messageInfo_DhtProviderRecord_Node.DiscardUnknown(m)
}

var xxx_messageInfo_DhtProviderRecord_Node proto.InternalMessageInfo

func (m *DhtProviderRecord_Node) GetIP() []byte {
	if m != nil {
		return m.IP
	}
	return nil
}

func (m *DhtProviderRecord_Node) GetUDP() uint32 {
	if m != nil && m.UDP != nil {
		return *m.UDP
	}
	return 0
}

func (m *DhtProviderRecord_Node) GetTCP() uint32 {
	if m != nil && m.TCP != nil {
		return *m.TCP
	}
	return 0
}

func (m *DhtProviderRecord_Node) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *DhtProviderRecord_Node) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

type DhtProviderRecord_Provider struct {
	Node                 *DhtProviderRecord_Node `protobuf:"bytes,1,req,name=Node" json:"Node,omitempty"`
	Extra                []byte                  `protobuf:"bytes,2,opt,name=Extra" json:"Extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *DhtProviderRecord_Provider) Reset()         { *m = DhtProviderRecord_Provider{} }
func (m *DhtProviderRecord_Provider) String() string { return proto.CompactTextString(m) }
func (*DhtProviderRecord_Provider) ProtoMessage()    {}
func (*DhtProviderRecord_Provider) Descriptor() ([]byte, []int) {
	return fileDescriptor_dhtmsg_0fb4397fe10fcc0f, []int{3, 1}
}
func (m *DhtProviderRecord_Provider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DhtProviderRecord_Provider.Unmarshal(m, b)
}
func (m *DhtProviderRecord_Provider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DhtProviderRecord_Provider.Marshal(b, m, deterministic)
}
func (dst *DhtProviderRecord_Provider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DhtProviderRecord_Provider.Merge(dst, src)
}
func (m *DhtProviderRecord_Provider) XXX_Size() int {
	return xxx_messageInfo_DhtProviderRecord_Provider.Size(m)
}
func (m *DhtProviderRecord_Provider) XXX_DiscardUnknown() {
	xxx_messageInfo_DhtProviderRecord_Provider.DiscardUnknown(m)
}

var xxx_messageInfo_DhtProviderRecord_Provider proto.InternalMessageInfo

func (m *DhtProviderRecord_Provider) GetNode() *DhtProviderRecord_Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *DhtProviderRecord_Provider) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

func init() {
	proto.RegisterType((*DhtPackage)(nil), "dhtmsg.pb.DhtPackage")
	proto.RegisterType((*DhtMessage)(nil), "dhtmsg.pb.DhtMessage")
	proto.RegisterType((*DhtMessage_Node)(nil), "dhtmsg.pb.DhtMessage.Node")
	proto.RegisterType((*DhtMessage_Value)(nil), "dhtmsg.pb.DhtMessage.Value")
	proto.RegisterType((*DhtMessage_Provider)(nil), "dhtmsg.pb.DhtMessage.Provider")
	proto.RegisterType((*DhtMessage_Protocol)(nil), "dhtmsg.pb.DhtMessage.Protocol")
	proto.RegisterType((*DhtMessage_Handshake)(nil), "dhtmsg.pb.DhtMessage.Handshake")
	proto.RegisterType((*DhtMessage_FindNode)(nil), "dhtmsg.pb.DhtMessage.FindNode")
	proto.RegisterType((*DhtMessage_Neighbors)(nil), "dhtmsg.pb.DhtMessage.Neighbors")
	proto.RegisterType((*DhtMessage_PutValue)(nil), "dhtmsg.pb.DhtMessage.PutValue")
	proto.RegisterType((*DhtMessage_GetValueReq)(nil), "dhtmsg.pb.DhtMessage.GetValueReq")
	proto.RegisterType((*DhtMessage_GetValueRsp)(nil), "dhtmsg.pb.DhtMessage.GetValueRsp")
	proto.RegisterType((*DhtMessage_PutProvider)(nil), "dhtmsg.pb.DhtMessage.PutProvider")
	proto.RegisterType((*DhtMessage_GetProviderReq)(nil), "dhtmsg.pb.DhtMessage.GetProviderReq")
	proto.RegisterType((*DhtMessage_GetProviderRsp)(nil), "dhtmsg.pb.DhtMessage.GetProviderRsp")
	proto.RegisterType((*DhtMessage_Ping)(nil), "dhtmsg.pb.DhtMessage.Ping")
	proto.RegisterType((*DhtMessage_Pong)(nil), "dhtmsg.pb.DhtMessage.Pong")
	proto.RegisterType((*DhtRecord)(nil), "dhtmsg.pb.DhtRecord")
	proto.RegisterType((*DhtProviderRecord)(nil), "dhtmsg.pb.DhtProviderRecord")
	proto.RegisterType((*DhtProviderRecord_Node)(nil), "dhtmsg.pb.DhtProviderRecord.Node")
	proto.RegisterType((*DhtProviderRecord_Provider)(nil), "dhtmsg.pb.DhtProviderRecord.Provider")
	proto.RegisterEnum("dhtmsg.pb.ProtocolId", ProtocolId_name, ProtocolId_value)
	proto.RegisterEnum("dhtmsg.pb.DhtMessage_MessageType", DhtMessage_MessageType_name, DhtMessage_MessageType_value)
	proto.RegisterEnum("dhtmsg.pb.DhtMessage_ConnectionType", DhtMessage_ConnectionType_name, DhtMessage_ConnectionType_value)
}

func init() { proto.RegisterFile("dhtmsg.proto", fileDescriptor_dhtmsg_0fb4397fe10fcc0f) }

var fileDescriptor_dhtmsg_0fb4397fe10fcc0f = []byte{
	// 1121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xcd, 0x6f, 0xe3, 0x44,
	0x14, 0x5f, 0x7f, 0xe5, 0xe3, 0x25, 0xed, 0x7a, 0x67, 0x17, 0x18, 0x05, 0x04, 0xd9, 0x68, 0xd1,
	0x56, 0x7b, 0xa8, 0xa0, 0x88, 0xcb, 0x02, 0x12, 0x21, 0x76, 0x5b, 0xb3, 0xad, 0x63, 0x26, 0x69,
	0x61, 0x4f, 0x55, 0xb6, 0x1e, 0x9c, 0xa8, 0x6d, 0xec, 0xda, 0xce, 0x8a, 0xfe, 0x0b, 0x1c, 0x11,
	0x67, 0x24, 0xa4, 0xfd, 0x3f, 0x10, 0xe2, 0xc8, 0xff, 0x81, 0xc4, 0x9d, 0x3b, 0x68, 0xc6, 0xe3,
	0x8f, 0x34, 0x89, 0x15, 0xb4, 0x8a, 0xb4, 0xa7, 0xcc, 0x7b, 0xfe, 0xbd, 0xef, 0x37, 0x6f, 0x5e,
	0xa0, 0xe9, 0x8e, 0xe3, 0xab, 0xc8, 0xdb, 0x0d, 0x42, 0x3f, 0xf6, 0x51, 0x3d, 0xa5, 0x5e, 0x74,
	0x66, 0x00, 0xc6, 0x38, 0x76, 0x46, 0xe7, 0x17, 0x23, 0x8f, 0xa2, 0xc7, 0xa0, 0x38, 0x13, 0x17,
	0x4b, 0x6d, 0x79, 0x67, 0x7b, 0xef, 0xad, 0xdd, 0x0c, 0xb6, 0xeb, 0x30, 0xb9, 0x73, 0xff, 0xd2,
	0x72, 0x09, 0x43, 0xa0, 0x47, 0xb0, 0xe5, 0x8c, 0x6e, 0x2e, 0xfd, 0x91, 0x7b, 0x44, 0xa7, 0x5e,
	0x3c, 0xc6, 0x72, 0x5b, 0xde, 0xd9, 0x22, 0xf3, 0x4c, 0x84, 0xa1, 0x2a, 0x18, 0x58, 0x69, 0x4b,
	0x3b, 0x4d, 0x92, 0x92, 0x9d, 0x5f, 0xde, 0xe3, 0x76, 0x8f, 0x69, 0x14, 0x31, 0xbb, 0x9f, 0x41,
	0xf5, 0x2a, 0xf2, 0x86, 0x37, 0x01, 0x15, 0xb6, 0x1f, 0x16, 0x6c, 0xe7, 0xb8, 0x5d, 0xf1, 0xcb,
	0x80, 0x24, 0x95, 0x40, 0x5f, 0x40, 0x7d, 0x3c, 0x9a, 0xba, 0xd1, 0x78, 0x74, 0x41, 0xb1, 0xdc,
	0x96, 0x76, 0x1a, 0x7b, 0x1f, 0x2c, 0x17, 0x3f, 0x4c, 0x61, 0x24, 0x97, 0x40, 0x4f, 0xa1, 0xf6,
	0xfd, 0x64, 0xea, 0xda, 0xbe, 0x4b, 0xb9, 0x97, 0x8d, 0xbd, 0xf7, 0x97, 0x4b, 0xef, 0x0b, 0x14,
	0xc9, 0xf0, 0xcc, 0xf4, 0x94, 0x4e, 0xbc, 0xf1, 0x0b, 0x3f, 0x8c, 0xb0, 0x5a, 0x66, 0xda, 0x4e,
	0x61, 0x24, 0x97, 0x60, 0xa6, 0x83, 0x59, 0x7c, 0x3a, 0xba, 0x9c, 0x51, 0xac, 0x95, 0x99, 0x76,
	0x04, 0x8a, 0x64, 0x78, 0xd4, 0x83, 0x86, 0x47, 0x05, 0x97, 0x5e, 0xe3, 0x0a, 0x17, 0x5f, 0x91,
	0xb6, 0x83, 0x1c, 0x48, 0x8a, 0x52, 0x73, 0x4a, 0xa2, 0x00, 0x57, 0xd7, 0x52, 0x12, 0x05, 0xa4,
	0x28, 0xc5, 0x94, 0x04, 0xb3, 0xd8, 0x09, 0xfd, 0x97, 0x13, 0x97, 0x86, 0xb8, 0x56, 0xa6, 0xc4,
	0xc9, 0x81, 0xa4, 0x28, 0x85, 0x8e, 0x60, 0xdb, 0xa3, 0xf9, 0x37, 0x7a, 0x8d, 0xeb, 0x5c, 0xcf,
	0xa3, 0x95, 0xce, 0x14, 0xb0, 0xe4, 0x96, 0xec, 0x6d, 0x6d, 0x51, 0x80, 0x61, 0x5d, 0x6d, 0x51,
	0x40, 0x6e, 0xc9, 0xa2, 0x5d, 0x50, 0x83, 0xc9, 0xd4, 0xc3, 0x0d, 0xae, 0xa3, 0xb5, 0x22, 0xb2,
	0xc9, 0xd4, 0x23, 0x1c, 0xc7, 0xf1, 0xfe, 0xd4, 0xc3, 0xcd, 0x52, 0xbc, 0xcf, 0xf1, 0xfe, 0xd4,
	0x6b, 0xfd, 0x2c, 0x81, 0xca, 0xdb, 0x69, 0x1b, 0x64, 0xcb, 0xe1, 0x37, 0xa0, 0x49, 0x64, 0xcb,
	0x41, 0x3a, 0x28, 0x27, 0x86, 0x23, 0xee, 0x16, 0x3b, 0x32, 0xce, 0xb0, 0xe7, 0x60, 0x25, 0xe1,
	0x0c, 0x7b, 0x0e, 0x7a, 0x1b, 0x2a, 0x4c, 0xd6, 0x72, 0xb1, 0xca, 0xe5, 0x04, 0x85, 0xbe, 0x84,
	0x5a, 0xcf, 0x9f, 0x4e, 0xf9, 0x9d, 0xd2, 0xf8, 0x9d, 0x5a, 0x11, 0x3c, 0x43, 0xd1, 0xf3, 0x78,
	0xe2, 0x73, 0x2c, 0xc9, 0xa4, 0x5a, 0x5d, 0xd0, 0x92, 0x56, 0xd3, 0x41, 0x79, 0x46, 0x6f, 0x84,
	0x5f, 0xec, 0xc8, 0x38, 0xa7, 0xa3, 0x4b, 0xee, 0x58, 0x93, 0xb0, 0x23, 0x7a, 0x00, 0x9a, 0xf9,
	0x43, 0x1c, 0x8e, 0xc4, 0x45, 0x4f, 0x88, 0x96, 0x0b, 0xb5, 0xac, 0xc2, 0x8b, 0x5a, 0x3e, 0x02,
	0x8d, 0x39, 0x1b, 0x61, 0xb9, 0xad, 0xac, 0x4e, 0x14, 0xbf, 0x72, 0x09, 0x70, 0x85, 0x15, 0x93,
	0x5b, 0xe1, 0xf3, 0x69, 0xfd, 0x09, 0xc6, 0x42, 0xa0, 0x61, 0x16, 0x02, 0x0d, 0x5b, 0x7f, 0x4b,
	0x50, 0xcf, 0x26, 0x04, 0xfb, 0x6e, 0x4c, 0x42, 0xae, 0x48, 0x23, 0xec, 0x58, 0xc8, 0xb4, 0x3c,
	0x97, 0xe9, 0xa4, 0x6a, 0xca, 0xed, 0xaa, 0xa9, 0x0b, 0x55, 0xd3, 0xf2, 0xaa, 0xb5, 0x84, 0xcb,
	0xf6, 0xec, 0x0a, 0x57, 0x38, 0x3b, 0xa3, 0xd1, 0xe7, 0x50, 0x4f, 0x9d, 0x8d, 0x70, 0x95, 0xa7,
	0x66, 0xd5, 0x58, 0x10, 0x30, 0x92, 0x0b, 0x70, 0x6f, 0x5c, 0x5c, 0x6b, 0xcb, 0x3b, 0x2a, 0x91,
	0x2d, 0x37, 0x4f, 0x59, 0xbd, 0x98, 0xb2, 0x57, 0x12, 0xd4, 0xd2, 0x79, 0xc6, 0xfa, 0x75, 0x3f,
	0xf4, 0xaf, 0x78, 0xac, 0xe5, 0x65, 0xe0, 0x38, 0xf4, 0x04, 0xe4, 0xa1, 0xcf, 0x93, 0x50, 0x8e,
	0x96, 0x87, 0x3e, 0x4b, 0xda, 0x70, 0x14, 0x7a, 0x34, 0x16, 0x09, 0x12, 0x94, 0x70, 0x53, 0x5d,
	0x74, 0x53, 0x2b, 0xba, 0xf9, 0x9b, 0x04, 0xf5, 0x6c, 0x72, 0x6e, 0xd4, 0xcf, 0xac, 0x17, 0x95,
	0x75, 0x7b, 0x71, 0xbd, 0x08, 0x7e, 0x97, 0xa0, 0x96, 0x4e, 0xef, 0x8d, 0x06, 0xf0, 0x09, 0x54,
	0xb8, 0x91, 0x34, 0x82, 0x77, 0x97, 0xe3, 0x93, 0xa9, 0x2d, 0xa0, 0x6b, 0xc6, 0xf0, 0xab, 0x04,
	0x8d, 0xc2, 0x13, 0xb2, 0xd1, 0x30, 0xc4, 0x94, 0x50, 0xf2, 0x29, 0xb1, 0x9e, 0x8f, 0xff, 0x14,
	0x7d, 0x4c, 0x66, 0xf6, 0xc6, 0x7c, 0xfc, 0x58, 0x0c, 0x46, 0xb1, 0x2e, 0x94, 0x66, 0x5a, 0x8c,
	0xd0, 0xac, 0xbd, 0xd4, 0xb2, 0x37, 0x61, 0xb1, 0xbd, 0xb4, 0xc5, 0xb0, 0x2b, 0xc5, 0xb0, 0xff,
	0x94, 0xa0, 0x51, 0x78, 0x53, 0x37, 0x1a, 0xf6, 0xd3, 0x7c, 0x98, 0xf3, 0xfa, 0x94, 0x8d, 0xa5,
	0xe4, 0xed, 0xcc, 0x87, 0xff, 0x7a, 0x45, 0x7c, 0x25, 0xc1, 0xf6, 0xfc, 0xcb, 0xfe, 0x46, 0xf6,
	0xda, 0x4f, 0xf2, 0xbc, 0x9b, 0x1b, 0x6e, 0xb7, 0xd7, 0xc9, 0xbb, 0x08, 0x51, 0x5d, 0xf2, 0xe8,
	0x6a, 0xff, 0x6f, 0xd0, 0x55, 0x16, 0x93, 0x52, 0x2d, 0x26, 0xe5, 0x47, 0x09, 0x54, 0x47, 0x6c,
	0x3f, 0x9b, 0xac, 0xd8, 0x80, 0x5e, 0xf3, 0x2c, 0xa8, 0x84, 0x1d, 0x73, 0x67, 0xd4, 0x05, 0x67,
	0xfc, 0x37, 0xc3, 0x99, 0xce, 0x5f, 0x12, 0x34, 0x0a, 0x7f, 0x5c, 0xd0, 0x3d, 0xd8, 0x3a, 0xb6,
	0x8c, 0xb3, 0xc3, 0xae, 0x6d, 0x0c, 0x0e, 0xbb, 0xcf, 0x4c, 0xfd, 0x0e, 0xd2, 0xa1, 0xc9, 0x58,
	0xfb, 0x96, 0x6d, 0xd8, 0x7d, 0xc3, 0xd4, 0xa5, 0x14, 0x64, 0x9b, 0xd6, 0xc1, 0xe1, 0x57, 0x7d,
	0x32, 0xd0, 0xe5, 0x14, 0xe4, 0x9c, 0x0c, 0x4f, 0xbb, 0x47, 0x27, 0xa6, 0xae, 0xa0, 0x07, 0xa0,
	0x33, 0xce, 0x81, 0x99, 0x70, 0xce, 0x88, 0xf9, 0x8d, 0xae, 0x2e, 0x72, 0x07, 0x8e, 0xae, 0xa1,
	0xfb, 0x70, 0x57, 0x48, 0x3b, 0xa4, 0x7f, 0x6a, 0x19, 0x26, 0xd1, 0x2b, 0xe8, 0x1d, 0xb8, 0x2f,
	0xa0, 0x29, 0x93, 0xeb, 0xa8, 0x2e, 0xfd, 0x30, 0x70, 0xf4, 0x1a, 0x6a, 0x42, 0x8d, 0xab, 0xb1,
	0xec, 0x03, 0xbd, 0x9e, 0x51, 0x7d, 0xfb, 0x40, 0x87, 0xce, 0xd7, 0xb0, 0x3d, 0xbf, 0x4c, 0xa2,
	0x06, 0x54, 0x7b, 0x7d, 0x7b, 0x78, 0x66, 0xf7, 0xf5, 0x3b, 0x0c, 0xcc, 0x89, 0xe7, 0xe6, 0x40,
	0x97, 0x32, 0xea, 0xb8, 0xfb, 0x5c, 0x97, 0xd1, 0x5d, 0x68, 0x70, 0x6a, 0xbf, 0x6b, 0x1d, 0x99,
	0x86, 0xae, 0x74, 0x2c, 0xa8, 0x1b, 0xe3, 0x98, 0xd0, 0x73, 0x3f, 0xe4, 0xbb, 0xda, 0x45, 0xbe,
	0x3a, 0x5e, 0xd0, 0x1b, 0x96, 0xe9, 0x97, 0x7c, 0x04, 0x27, 0xab, 0x58, 0x42, 0x2c, 0x5f, 0x0f,
	0x3b, 0x7f, 0xc8, 0x70, 0x8f, 0xfd, 0xc7, 0xcd, 0xa6, 0xca, 0x0a, 0x9d, 0x3d, 0xa8, 0x07, 0x02,
	0x93, 0xae, 0xa4, 0x1f, 0xce, 0xb7, 0xc0, 0xbc, 0x8a, 0xfc, 0xbe, 0xe5, 0x72, 0x2b, 0x36, 0xd4,
	0xf1, 0x06, 0x16, 0xfc, 0xe5, 0xb3, 0xe9, 0xdb, 0xc2, 0xc6, 0xfd, 0x69, 0x62, 0x55, 0x34, 0xff,
	0xc3, 0xd2, 0x58, 0x92, 0x3b, 0xc0, 0x9d, 0xcc, 0x14, 0xcb, 0x05, 0xc5, 0x4f, 0x1e, 0x03, 0xe4,
	0x2b, 0x34, 0x2b, 0xac, 0x63, 0x19, 0x67, 0xc6, 0xe1, 0x90, 0x17, 0x96, 0x13, 0xe6, 0x77, 0x43,
	0xfd, 0x5f, 0xe9, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x37, 0xad, 0x54, 0xab, 0x6b, 0x10, 0x00,
	0x00,
}
