# This is a TOML document for default config

name = "my name"

[network]
bootnode = ["B62D9CFDF01C768F23CA0C4190675C8DE53B52E43957E3CB450D60B93C12BAA8ACEFCDA83E49304C92953C88BAE0A85BEB5CDA787594073642C602228DF5DD5A@3.1.169.4:30304:30304"]
listen = ["0.0.0.0:7352"]

app_type = 2
name = "test"
validator = true
bootstrap_node = false
bootstrap_nodes = ["B62D9CFDF01C768F23CA0C4190675C8DE53B52E43957E3CB450D60B93C12BAA8ACEFCDA83E49304C92953C88BAE0A85BEB5CDA787594073642C602228DF5DD5A@3.1.169.4:30304:30304"]
dht_bootstrap_nodes = ["B62D9CFDF01C768F23CA0C4190675C8DE53B52E43957E3CB450D60B93C12BAA8ACEFCDA83E49304C92953C88BAE0A85BEB5CDA787594073642C602228DF5DD5A@3.1.169.4:40405:40405"]
local_node_ip = "0.0.0.0"
local_udp_port = 30303
local_tcp_port = 30303
local_dht_ip = "0.0.0.0"
node_data_path = ""
node_database = "nodes"
subnet_mask_bits = 0
ev_keep_time = 60
dedup_time = 60
bootstrap_time = 4
nat_type = "none"
gateway_ip = "0.0.0.0"

[chain]
chain_id = 1
data_dir = "data"
key_dir = "keystore"
genesis = "genesis.toml"
mine = false

[rpc]
ipc_path = "gyee.ipc"
rpc_listen = ["127.0.0.1:7353"]
http_listen = ["127.0.0.1:7354"]

[app]
log_level = "debug"
log_file = "logs/log"
enable_crash_report = true
crash_report_url =["crash.yeecall.com"]

[metrics]
enable_metrics = false
enable_metrics_report = false
metrics_report_url = ["", ""]


[misc]