// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package rpcpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Request message of non params.
type NonParamsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NonParamsRequest) Reset()         { *m = NonParamsRequest{} }
func (m *NonParamsRequest) String() string { return proto.CompactTextString(m) }
func (*NonParamsRequest) ProtoMessage()    {}
func (*NonParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_92e5449a6d02e6a8, []int{0}
}
func (m *NonParamsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NonParamsRequest.Unmarshal(m, b)
}
func (m *NonParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NonParamsRequest.Marshal(b, m, deterministic)
}
func (dst *NonParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonParamsRequest.Merge(dst, src)
}
func (m *NonParamsRequest) XXX_Size() int {
	return xxx_messageInfo_NonParamsRequest.Size(m)
}
func (m *NonParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NonParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NonParamsRequest proto.InternalMessageInfo

type BlockResponse struct {
	// block hash hex string
	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// block parent hash
	ParentHash string `protobuf:"bytes,2,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	// block height
	Height uint64 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	// block timestamp
	Timestamp uint64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// block chain id
	ChainId uint32 `protobuf:"varint,5,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// consensus root hex string
	ConsensusRoot string `protobuf:"bytes,6,opt,name=consensus_root,json=consensusRoot,proto3" json:"consensus_root,omitempty"`
	// state root hex string
	StateRoot string `protobuf:"bytes,7,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	// transactions root hex string
	TxsRoot string `protobuf:"bytes,8,opt,name=txs_root,json=txsRoot,proto3" json:"txs_root,omitempty"`
	// receipts root hex string
	ReceiptsRoot         string   `protobuf:"bytes,9,opt,name=receipts_root,json=receiptsRoot,proto3" json:"receipts_root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockResponse) Reset()         { *m = BlockResponse{} }
func (m *BlockResponse) String() string { return proto.CompactTextString(m) }
func (*BlockResponse) ProtoMessage()    {}
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_92e5449a6d02e6a8, []int{1}
}
func (m *BlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockResponse.Unmarshal(m, b)
}
func (m *BlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockResponse.Marshal(b, m, deterministic)
}
func (dst *BlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockResponse.Merge(dst, src)
}
func (m *BlockResponse) XXX_Size() int {
	return xxx_messageInfo_BlockResponse.Size(m)
}
func (m *BlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlockResponse proto.InternalMessageInfo

func (m *BlockResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *BlockResponse) GetParentHash() string {
	if m != nil {
		return m.ParentHash
	}
	return ""
}

func (m *BlockResponse) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockResponse) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *BlockResponse) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *BlockResponse) GetConsensusRoot() string {
	if m != nil {
		return m.ConsensusRoot
	}
	return ""
}

func (m *BlockResponse) GetStateRoot() string {
	if m != nil {
		return m.StateRoot
	}
	return ""
}

func (m *BlockResponse) GetTxsRoot() string {
	if m != nil {
		return m.TxsRoot
	}
	return ""
}

func (m *BlockResponse) GetReceiptsRoot() string {
	if m != nil {
		return m.ReceiptsRoot
	}
	return ""
}

type GetBlockByHashRequest struct {
	// block hash hex string
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockByHashRequest) Reset()         { *m = GetBlockByHashRequest{} }
func (m *GetBlockByHashRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockByHashRequest) ProtoMessage()    {}
func (*GetBlockByHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_92e5449a6d02e6a8, []int{2}
}
func (m *GetBlockByHashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockByHashRequest.Unmarshal(m, b)
}
func (m *GetBlockByHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockByHashRequest.Marshal(b, m, deterministic)
}
func (dst *GetBlockByHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockByHashRequest.Merge(dst, src)
}
func (m *GetBlockByHashRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockByHashRequest.Size(m)
}
func (m *GetBlockByHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockByHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockByHashRequest proto.InternalMessageInfo

func (m *GetBlockByHashRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type GetBlockByHeightRequest struct {
	// block height
	Height               uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockByHeightRequest) Reset()         { *m = GetBlockByHeightRequest{} }
func (m *GetBlockByHeightRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockByHeightRequest) ProtoMessage()    {}
func (*GetBlockByHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_92e5449a6d02e6a8, []int{3}
}
func (m *GetBlockByHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockByHeightRequest.Unmarshal(m, b)
}
func (m *GetBlockByHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockByHeightRequest.Marshal(b, m, deterministic)
}
func (dst *GetBlockByHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockByHeightRequest.Merge(dst, src)
}
func (m *GetBlockByHeightRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockByHeightRequest.Size(m)
}
func (m *GetBlockByHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockByHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockByHeightRequest proto.InternalMessageInfo

func (m *GetBlockByHeightRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

// Response message of node info.
type NodeInfoResponse struct {
	// the node ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// the node version.
	Version              uint32   `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeInfoResponse) Reset()         { *m = NodeInfoResponse{} }
func (m *NodeInfoResponse) String() string { return proto.CompactTextString(m) }
func (*NodeInfoResponse) ProtoMessage()    {}
func (*NodeInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_92e5449a6d02e6a8, []int{4}
}
func (m *NodeInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfoResponse.Unmarshal(m, b)
}
func (m *NodeInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfoResponse.Marshal(b, m, deterministic)
}
func (dst *NodeInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfoResponse.Merge(dst, src)
}
func (m *NodeInfoResponse) XXX_Size() int {
	return xxx_messageInfo_NodeInfoResponse.Size(m)
}
func (m *NodeInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfoResponse proto.InternalMessageInfo

func (m *NodeInfoResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NodeInfoResponse) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type NewAccountRequest struct {
	Passphrase           string   `protobuf:"bytes,1,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewAccountRequest) Reset()         { *m = NewAccountRequest{} }
func (m *NewAccountRequest) String() string { return proto.CompactTextString(m) }
func (*NewAccountRequest) ProtoMessage()    {}
func (*NewAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_92e5449a6d02e6a8, []int{5}
}
func (m *NewAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewAccountRequest.Unmarshal(m, b)
}
func (m *NewAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewAccountRequest.Marshal(b, m, deterministic)
}
func (dst *NewAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewAccountRequest.Merge(dst, src)
}
func (m *NewAccountRequest) XXX_Size() int {
	return xxx_messageInfo_NewAccountRequest.Size(m)
}
func (m *NewAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewAccountRequest proto.InternalMessageInfo

func (m *NewAccountRequest) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

type NewAccountResponse struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewAccountResponse) Reset()         { *m = NewAccountResponse{} }
func (m *NewAccountResponse) String() string { return proto.CompactTextString(m) }
func (*NewAccountResponse) ProtoMessage()    {}
func (*NewAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_92e5449a6d02e6a8, []int{6}
}
func (m *NewAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewAccountResponse.Unmarshal(m, b)
}
func (m *NewAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewAccountResponse.Marshal(b, m, deterministic)
}
func (dst *NewAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewAccountResponse.Merge(dst, src)
}
func (m *NewAccountResponse) XXX_Size() int {
	return xxx_messageInfo_NewAccountResponse.Size(m)
}
func (m *NewAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewAccountResponse proto.InternalMessageInfo

func (m *NewAccountResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*NonParamsRequest)(nil), "rpcpb.NonParamsRequest")
	proto.RegisterType((*BlockResponse)(nil), "rpcpb.BlockResponse")
	proto.RegisterType((*GetBlockByHashRequest)(nil), "rpcpb.GetBlockByHashRequest")
	proto.RegisterType((*GetBlockByHeightRequest)(nil), "rpcpb.GetBlockByHeightRequest")
	proto.RegisterType((*NodeInfoResponse)(nil), "rpcpb.NodeInfoResponse")
	proto.RegisterType((*NewAccountRequest)(nil), "rpcpb.NewAccountRequest")
	proto.RegisterType((*NewAccountResponse)(nil), "rpcpb.NewAccountResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdminServiceClient interface {
	NewAccount(ctx context.Context, in *NewAccountRequest, opts ...grpc.CallOption) (*NewAccountResponse, error)
}

type adminServiceClient struct {
	cc *grpc.ClientConn
}

func NewAdminServiceClient(cc *grpc.ClientConn) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) NewAccount(ctx context.Context, in *NewAccountRequest, opts ...grpc.CallOption) (*NewAccountResponse, error) {
	out := new(NewAccountResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.AdminService/NewAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
type AdminServiceServer interface {
	NewAccount(context.Context, *NewAccountRequest) (*NewAccountResponse, error)
}

func RegisterAdminServiceServer(s *grpc.Server, srv AdminServiceServer) {
	s.RegisterService(&_AdminService_serviceDesc, srv)
}

func _AdminService_NewAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).NewAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.AdminService/NewAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).NewAccount(ctx, req.(*NewAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdminService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpcpb.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewAccount",
			Handler:    _AdminService_NewAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

// ApiServiceClient is the client API for ApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApiServiceClient interface {
	NodeInfo(ctx context.Context, in *NonParamsRequest, opts ...grpc.CallOption) (*NodeInfoResponse, error)
	GetBlockByHash(ctx context.Context, in *GetBlockByHashRequest, opts ...grpc.CallOption) (*BlockResponse, error)
	GetBlockByHeight(ctx context.Context, in *GetBlockByHeightRequest, opts ...grpc.CallOption) (*BlockResponse, error)
}

type apiServiceClient struct {
	cc *grpc.ClientConn
}

func NewApiServiceClient(cc *grpc.ClientConn) ApiServiceClient {
	return &apiServiceClient{cc}
}

func (c *apiServiceClient) NodeInfo(ctx context.Context, in *NonParamsRequest, opts ...grpc.CallOption) (*NodeInfoResponse, error) {
	out := new(NodeInfoResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.ApiService/NodeInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) GetBlockByHash(ctx context.Context, in *GetBlockByHashRequest, opts ...grpc.CallOption) (*BlockResponse, error) {
	out := new(BlockResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.ApiService/GetBlockByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) GetBlockByHeight(ctx context.Context, in *GetBlockByHeightRequest, opts ...grpc.CallOption) (*BlockResponse, error) {
	out := new(BlockResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.ApiService/GetBlockByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServiceServer is the server API for ApiService service.
type ApiServiceServer interface {
	NodeInfo(context.Context, *NonParamsRequest) (*NodeInfoResponse, error)
	GetBlockByHash(context.Context, *GetBlockByHashRequest) (*BlockResponse, error)
	GetBlockByHeight(context.Context, *GetBlockByHeightRequest) (*BlockResponse, error)
}

func RegisterApiServiceServer(s *grpc.Server, srv ApiServiceServer) {
	s.RegisterService(&_ApiService_serviceDesc, srv)
}

func _ApiService_NodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NonParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).NodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.ApiService/NodeInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).NodeInfo(ctx, req.(*NonParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_GetBlockByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetBlockByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.ApiService/GetBlockByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetBlockByHash(ctx, req.(*GetBlockByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_GetBlockByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetBlockByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.ApiService/GetBlockByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetBlockByHeight(ctx, req.(*GetBlockByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApiService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpcpb.ApiService",
	HandlerType: (*ApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NodeInfo",
			Handler:    _ApiService_NodeInfo_Handler,
		},
		{
			MethodName: "GetBlockByHash",
			Handler:    _ApiService_GetBlockByHash_Handler,
		},
		{
			MethodName: "GetBlockByHeight",
			Handler:    _ApiService_GetBlockByHeight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_rpc_92e5449a6d02e6a8) }

var fileDescriptor_rpc_92e5449a6d02e6a8 = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x6f, 0x6f, 0xd3, 0x3c,
	0x10, 0x6f, 0xfa, 0x74, 0x4d, 0x73, 0xcf, 0x52, 0x8d, 0x13, 0xb0, 0xb4, 0x1a, 0xa3, 0x32, 0x42,
	0xaa, 0x84, 0x54, 0x89, 0xed, 0x2d, 0x42, 0xea, 0x90, 0x80, 0xf1, 0x62, 0x42, 0xd9, 0x07, 0xa8,
	0xbc, 0xe4, 0x20, 0x16, 0xd4, 0x36, 0xb6, 0x3b, 0xc6, 0x67, 0xe1, 0xcb, 0xf1, 0x51, 0x50, 0x5c,
	0xa7, 0x4d, 0xb7, 0xf2, 0x2e, 0xf7, 0xfb, 0x73, 0x67, 0xff, 0xce, 0x81, 0xc4, 0xe8, 0x62, 0xa6,
	0x8d, 0x72, 0x0a, 0x0f, 0x8c, 0x2e, 0xf4, 0x0d, 0x43, 0x38, 0xba, 0x52, 0xf2, 0x33, 0x37, 0x7c,
	0x69, 0x73, 0xfa, 0xb1, 0x22, 0xeb, 0xd8, 0xef, 0x2e, 0xa4, 0x17, 0xdf, 0x55, 0xf1, 0x2d, 0x27,
	0xab, 0x95, 0xb4, 0x84, 0x08, 0xbd, 0x8a, 0xdb, 0x2a, 0x8b, 0x26, 0xd1, 0x34, 0xc9, 0xfd, 0x37,
	0x3e, 0x87, 0xff, 0x35, 0x37, 0x24, 0xdd, 0xc2, 0x53, 0x5d, 0x4f, 0xc1, 0x1a, 0xfa, 0x58, 0x0b,
	0x9e, 0x42, 0xbf, 0x22, 0xf1, 0xb5, 0x72, 0xd9, 0x7f, 0x93, 0x68, 0xda, 0xcb, 0x43, 0x85, 0x27,
	0x90, 0x38, 0xb1, 0x24, 0xeb, 0xf8, 0x52, 0x67, 0x3d, 0x4f, 0x6d, 0x01, 0x1c, 0xc1, 0xa0, 0xa8,
	0xb8, 0x90, 0x0b, 0x51, 0x66, 0x07, 0x93, 0x68, 0x9a, 0xe6, 0xb1, 0xaf, 0x2f, 0x4b, 0x7c, 0x09,
	0xc3, 0xa2, 0x3e, 0x8e, 0xb4, 0x2b, 0xbb, 0x30, 0x4a, 0xb9, 0xac, 0xef, 0x87, 0xa6, 0x1b, 0x34,
	0x57, 0xca, 0xe1, 0x33, 0x00, 0xeb, 0xb8, 0xa3, 0xb5, 0x24, 0xf6, 0x92, 0xc4, 0x23, 0x9e, 0x1e,
	0xc1, 0xc0, 0xdd, 0x05, 0xff, 0xc0, 0x93, 0xb1, 0xbb, 0x5b, 0x3b, 0x5f, 0x40, 0x6a, 0xa8, 0x20,
	0xa1, 0x5d, 0xe0, 0x13, 0xcf, 0x1f, 0x36, 0x60, 0x2d, 0x62, 0xaf, 0xe0, 0xc9, 0x07, 0x72, 0x3e,
	0x9f, 0x8b, 0x5f, 0xf5, 0x45, 0x43, 0x6c, 0xfb, 0x42, 0x62, 0xaf, 0xe1, 0xb8, 0x25, 0xf6, 0xf7,
	0x6f, 0xe4, 0xdb, 0x78, 0xa2, 0x76, 0x3c, 0xec, 0x4d, 0xbd, 0x91, 0x92, 0x2e, 0xe5, 0x17, 0xb5,
	0xc9, 0x7f, 0x08, 0x5d, 0x51, 0x86, 0xc6, 0x5d, 0x51, 0x62, 0x06, 0xf1, 0x2d, 0x19, 0x2b, 0x94,
	0xf4, 0xb9, 0xa7, 0x79, 0x53, 0xb2, 0x73, 0x78, 0x74, 0x45, 0x3f, 0xe7, 0x45, 0xa1, 0x56, 0x72,
	0x33, 0xea, 0x14, 0x40, 0x73, 0x6b, 0x75, 0x65, 0xb8, 0xa5, 0xd0, 0xa6, 0x85, 0xb0, 0x19, 0x60,
	0xdb, 0x14, 0x86, 0x66, 0x10, 0xf3, 0xb2, 0x34, 0x64, 0x6d, 0xb0, 0x34, 0xe5, 0xd9, 0x35, 0x1c,
	0xce, 0xcb, 0xa5, 0x90, 0xd7, 0x64, 0x6e, 0x45, 0x41, 0xf8, 0x0e, 0x60, 0xeb, 0xc7, 0x6c, 0xe6,
	0x9f, 0xd6, 0xec, 0xc1, 0x39, 0xc6, 0xa3, 0x3d, 0xcc, 0x7a, 0x18, 0xeb, 0x9c, 0xfd, 0x89, 0x00,
	0xe6, 0x5a, 0x34, 0x3d, 0xdf, 0xc2, 0xa0, 0x89, 0x01, 0x8f, 0x1b, 0xdf, 0xbd, 0x97, 0x3a, 0xde,
	0x12, 0xbb, 0x81, 0xb1, 0x0e, 0xbe, 0x87, 0xe1, 0xee, 0x9a, 0xf0, 0x24, 0x88, 0xf7, 0x6e, 0x6f,
	0xfc, 0x38, 0xb0, 0x3b, 0x0f, 0x9f, 0x75, 0xf0, 0x13, 0x1c, 0xdd, 0xdf, 0x20, 0x9e, 0x3e, 0xec,
	0xd4, 0x5e, 0xed, 0xbf, 0x7a, 0xdd, 0xf4, 0xfd, 0xaf, 0x77, 0xfe, 0x37, 0x00, 0x00, 0xff, 0xff,
	0x71, 0x6b, 0x5f, 0xb5, 0x87, 0x03, 0x00, 0x00,
}
